### PR TITLE
Update aws sqs-exporter

### PR DESCRIPTION
**Pull request by ashiddo11**
@brian-brazil I had a lot of problems with https://github.com/jmal98/sqs_exporter. It was working a few weeks ago and suddenly stopped. There weren't much logs to help troubleshoot so I wrote a simple sqs exporter in golang.

### CODE REVIEW

**Comment by brian-brazil** [comment]
What's better about this exporter that justifies replacing the existing one? Have you tried working with the author of the existing one to improve it?

**Comment by ashiddo11** [comment]
Haven't got any response, been trying for a weeks. So I came up with this as a fix and noticed others had issues with the other one.

**Comment by brian-brazil** [comment]
I don't see any PRs or issues filed against that repo, how did you come to the conclusion that the other repo is abandoned?

**Comment by ashiddo11** [comment]
Issue has been fixed on the original exporter. I'll close this PR

**Pull request closed without merging**
