### PR TITLE
Add nomad exporter

### PR DESCRIPTION
**Pull request by pcarranza**
@brian-brazil or @SuperQ I can haz PR?

### CODE REVIEW

**Comment by SuperQ** [comment]
It looks like this is a fork of an exporter.  Why not push your changes upstream?

Also, it looks like this exporter doesn't have a [port allocation](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) and is using one from another exporter.

**Comment by pcarranza** [comment]
I can try pushing upstream, but it changed so much that I'm not even sure it will be accepted.

**Comment by pcarranza** [comment]
https://github.com/Nomon/nomad-exporter/pull/25 maybe it gets accepted, dunno.

**Comment by brian-brazil** [comment]
Thanks for sharing, in addition to Ben's comments here's some things you could improve:

raft_peers is a bit odd. This is a kube-state-metrics like exporter in which talking to a random node is okay, however raft_peers is about the cluster itself so you should have an exporter beside every node to get that in case it differs. I'd suggest dropping both that and the leader logic to avoid confusion and as the leader logic seems fragile.

Rather than having nomad_client_errors_total which would only spot errors in the previous scrape, I'd suggest either setting nomad_up to 0 if there is an error or failing the scrape. Partial data is virtually impossible to work with for users.

Info metrics should usually be constant over time, so I'd move each of status and drain to separate boolean gauge metrics.  serf_lan_member_status is an info metric, so should end in _info.

deployment_task_group_placed_allocs_total is a gauge, so should not have a _total suffix which is for counters.

allocation_memory_rss_bytes_limit limit should go before bytes, so the unit is always at the end of the metric

task_cpu_percent prefer ratios to percentages, as they're the base units.

**Comment by brian-brazil** [comment]
Also, deploymentTaskGroupDesiredCanaries and a few others in collectDeploymentMetrics are not using ConstMetrics.

**Comment by pcarranza** [comment]
Thanks @brian-brazil 

The reason to have partial metrics is that we have noticed that sometimes the API gets a bit flaky and it fails, I didn't want to lose a scrape just because some section of it couldn't make it.

Regarding the leader logic, I know it's a bit brittle, but I do want to avoid impacting the nodes as it seems that to get the nodes and allocations metrics nomad is effectively issuing queries to all the nodes synchronously 😒, therefore I wanted to reduce the impact of querying for metrics to a single node.

I will review the metrics names. Only one question:

> task_cpu_percent prefer ratios to percentages, as they're the base units

You mean to change the metric name or to get it differently? I was investigating nomad api and the way they declare it is by percentage, I'm not sure it's the appropriate unit though as it can go over 100, the thing is I didn't dig deep enough to understand exactly what is it.

BTW, just changed the port to the reserved one.

**Comment by brian-brazil** [comment]
> The reason to have partial metrics is that we have noticed that sometimes the API gets a bit flaky and it fails, I didn't want to lose a scrape just because some section of it couldn't make it.

If you want to do that then you'll need a metric indicating which parts failed, and more importantly don't return any metrics for those parts.

> I wanted to reduce the impact of querying for metrics to a single node.

That's okay, as long as the leader and peers metrics aren't present. Otherwise you're mixing two different deployment models in one exporter.

> You mean to change the metric name or to get it differently?

Change the metric name.

> I'm not sure it's the appropriate unit though as it can go over 100

Hmm, are tasks allowed to burst above their allocation for cpu?

**Comment by pcarranza** [comment]
@brian-brazil reiterating a bit on this

> raft_peers is a bit odd. This is a kube-state-metrics like exporter in which talking to a random node is okay, however raft_peers is about the cluster itself so you should have an exporter beside every node to get that in case it differs. I'd suggest dropping both that and the leader logic to avoid confusion and as the leader logic seems fragile.

I see what you mean, in fact having the peers from each node perspective makes sense, the only I think I want to extract from the server is the state metrics, so maybe it makes sense to split this -> always take the peers metric for all the hosts (this is intended to be executed next to every nomad server, which is a raft peer), then only take the stats metrics from the leader.

What I don't want is all the hosts querying all the other hosts for stats on every scrape.

**Comment by pcarranza** [comment]
Changes visible here: https://github.com/pcarranza/nomad-exporter/pull/1

**Comment by brian-brazil** [comment]
> always take the peers metric for all the hosts (this is intended to be executed next to every nomad server, which is a raft peer), then only take the stats metrics from the leader.

This is not the architecture for exporters though, it's usually 1:1. This would usually be a separate exporter for the metrics of nomad itself so that scheduling and service discovery remains with Prometheus. Thus I suggest dropping these metrics for simplicity.

**Comment by brian-brazil** [comment]
Looks like the upstream is abandoned, an attempt was made to work upsteam, and this one has a small community already so I think it's okay to list it.

Can you add the DCO?

**Comment by pcarranza** [comment]
Done, and updated the url as I moved the project to gitlab.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
