### PR TITLE
Added CockroachDB (no exporter needed, built-in endpoint)

### PR DESCRIPTION
**Pull request by lgueye**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?


I'd suggest looking at using the Prometheus client directly, it'll be simpler and more efficient.

**Comment by lgueye** [comment]
@brian-brazil I don't know what a DCO is but I'll take a look

**Comment by lgueye** [comment]
@brian-brazil figured out what it is. I might ask cockroachdb developers to do it since I'm not an expert on their licensing strategy.
Thank you for your time

**Comment by brian-brazil** [comment]
`git commit --amend -s` should do it, then force push.

**Pull request closed without merging**
