### PR TITLE
docs/instrumenting/exporters: add ejabberd-exporter

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by SuperQ** [comment]
I think https://github.com/skythet/ejabberd-prometheus-exporter might be a better option, as it is a native module.

**Comment by genofire** [comment]
a single commit over 2 years, that is no maintenance ...
i also like the  set of metrics more ...

skynet:
```
ejabberd_memory_total_bytes{node="'ejabberd@apus.h.sum7.eu'"} 55998200
ejabberd_memory_processes_bytes{node="'ejabberd@apus.h.sum7.eu'"} 11338760
ejabberd_memory_processes_used_bytes{node="'ejabberd@apus.h.sum7.eu'"} 11335912
ejabberd_memory_system_bytes{node="'ejabberd@apus.h.sum7.eu'"} 44659440
ejabberd_memory_atom_bytes{node="'ejabberd@apus.h.sum7.eu'"} 984241
ejabberd_memory_atom_used_bytes{node="'ejabberd@apus.h.sum7.eu'"} 982397
ejabberd_memory_binary_bytes{node="'ejabberd@apus.h.sum7.eu'"} 2560552
ejabberd_memory_code_bytes{node="'ejabberd@apus.h.sum7.eu'"} 20111338
ejabberd_memory_ets_bytes{node="'ejabberd@apus.h.sum7.eu'"} 5312288
ejabberd_total_run_queue_lengths{node="'ejabberd@apus.h.sum7.eu'"} 1
ejabberd_total_active_tasks{node="'ejabberd@apus.h.sum7.eu'"} 2
ejabberd_context_switches{node="'ejabberd@apus.h.sum7.eu'"} 704400
ejabberd_gc_number{node="'ejabberd@apus.h.sum7.eu'"} 103603
ejabberd_gc_words_reclaimed_total{node="'ejabberd@apus.h.sum7.eu'"} 314414446
ejabberd_io_input_bytes{node="'ejabberd@apus.h.sum7.eu'"} 56630788
ejabberd_io_output_bytes{node="'ejabberd@apus.h.sum7.eu'"} 20995403
ejabberd_reductions_total{node="'ejabberd@apus.h.sum7.eu'"} 121725686
ejabberd_reductions_since_last_call{node="'ejabberd@apus.h.sum7.eu'"} 19707
ejabberd_run_time_total_seconds{node="'ejabberd@apus.h.sum7.eu'"} 52.393
ejabberd_allocated_areas_sys_misc_bytes{node="'ejabberd@apus.h.sum7.eu'"} 58568
ejabberd_allocated_areas_static_bytes{node="'ejabberd@apus.h.sum7.eu'"} 527312
ejabberd_allocated_areas_atom_space_bytes{node="'ejabberd@apus.h.sum7.eu'"} 524416
ejabberd_allocated_areas_atom_space_used_bytes{node="'ejabberd@apus.h.sum7.eu'"} 522644
ejabberd_allocated_areas_atom_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 459825
ejabberd_allocated_areas_module_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 226296
ejabberd_allocated_areas_export_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 592300
ejabberd_allocated_areas_export_list_bytes{node="'ejabberd@apus.h.sum7.eu'"} 2525424
ejabberd_allocated_areas_register_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 1692
ejabberd_allocated_areas_fun_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 25738
ejabberd_allocated_areas_module_refs_bytes{node="'ejabberd@apus.h.sum7.eu'"} 25872
ejabberd_allocated_areas_loaded_code_bytes{node="'ejabberd@apus.h.sum7.eu'"} 16715708
ejabberd_allocated_areas_dist_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 37371
ejabberd_allocated_areas_node_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 2747
ejabberd_allocated_areas_bits_bufs_size_bytes{node="'ejabberd@apus.h.sum7.eu'"} 0
ejabberd_allocated_areas_bif_timer_bytes{node="'ejabberd@apus.h.sum7.eu'"} 0
ejabberd_allocated_areas_process_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 3145728
ejabberd_allocated_areas_port_table_bytes{node="'ejabberd@apus.h.sum7.eu'"} 393216
ejabberd_allocated_areas_ets_misc_bytes{node="'ejabberd@apus.h.sum7.eu'"} 131072
ejabberd_port_count{node="'ejabberd@apus.h.sum7.eu'"} 473
ejabberd_port_limit{node="'ejabberd@apus.h.sum7.eu'"} 32768
ejabberd_process_count{node="'ejabberd@apus.h.sum7.eu'"} 934
ejabberd_process_limit{node="'ejabberd@apus.h.sum7.eu'"} 262144
```
greizgh:
```
# HELP ejabberd_connected_users Number of connected users
# TYPE ejabberd_connected_users gauge
ejabberd_connected_users 101
# HELP ejabberd_incoming_s2s_connections Number of s2s incoming connections
# TYPE ejabberd_incoming_s2s_connections gauge
ejabberd_incoming_s2s_connections 0
# HELP ejabberd_outgoing_s2s_connections Number of s2s outgoing connections
# TYPE ejabberd_outgoing_s2s_connections gauge
ejabberd_outgoing_s2s_connections 170
# HELP ejabberd_mnesia_transaction_commits Number of mnesia transaction commits
# TYPE ejabberd_mnesia_transaction_commits counter
ejabberd_mnesia_transaction_commits 347
# HELP ejabberd_mnesia_transaction_failures Number of mnesia transaction failures
# TYPE ejabberd_mnesia_transaction_failures counter
ejabberd_mnesia_transaction_failures 6
# HELP ejabberd_mnesia_transaction_log_writes Number of mnesia transaction log writes
# TYPE ejabberd_mnesia_transaction_log_writes counter
ejabberd_mnesia_transaction_log_writes 4
# HELP ejabberd_users_registered Number of registered users
# TYPE ejabberd_users_registered gauge
ejabberd_users_registered 936
# HELP ejabberd_users_online Number of online users
# TYPE ejabberd_users_online gauge
ejabberd_users_online 101
# HELP ejabberd_users_online_node Number of online users served by this node
# TYPE ejabberd_users_online_node gauge
ejabberd_users_online_node 101
# HELP ejabberd_uptime Node uptime in seconds
# TYPE ejabberd_uptime gauge
ejabberd_uptime 331
# HELP ejabberd_processes Number of erlang processes
# TYPE ejabberd_processes gauge
ejabberd_processes 951
```

**Comment by brian-brazil** [comment]
Neither have much of a community, but ejabberd-prometheus-exporter superficially seems better as there's more than one contributor.

**Comment by genofire** [comment]
https://dev.sum7.eu/sum7/ejabberd-metrics is also a little new exporter by @mightyBroccoli and me.

Is this better?

**Pull request closed without merging**
