### PR TITLE
[WIP] Add initial blog code.

### PR DESCRIPTION
**Pull request by juliusv**
This is based roughly on

  http://clarkdave.net/2012/02/building-a-static-blog-with-nanoc/

with a lot of small modifications to make it fit the existing docs site.

Two things to do before removing the [WIP]:

- remove the test posts (I included them so reviewers can test it
  themselves and see what posts would look like)
- remove the "BLOG" link in the top menu until we have a real article

### CODE REVIEW

**Comment by juliusv** [comment]
@grobie @brian-brazil @beorn7

**Comment by juliusv** [comment]
Screenshot of the index feed page:

blog

**Comment by juliusv** [comment]
Screenshot of a specific post:

blog_post

**Comment by beorn7** [comment]
I might have missed the discussion... What is the idea behind creating a blog on the docs site? What is the connection to the Blogger.com blog?

**Comment by juliusv** [comment]
The blogger.com one was an initial attempt, but it has certain problems,
the biggest of which is that it's hard to style and not well integrated
with the rest of the site. Mostly due to a discussion with @grobie, I ended
up moving to this "native" nanoc blog.

**Comment by juliusv** [comment]
The general motivation to have a blog at all is that so far, we only have
scattered posts on various (mostly company) sites, and we want to start
blogging in a central location.

**Comment by fabxc** [comment]
I would reduce the text width a fair bit. Shorter lines are more appealing and most importantly faster to read (there's some science on that on the internet!).

**Comment by grobie** [comment]
Good point by @beorn7, this repository should probably be renamed to `site`/`web`/`prometheus.io` or something like that, as it doesn't only include the code for the documentation anymore.

In general I like the idea of having the blog here as well. Less tools/services around, no "who has access to our blog, I want to fix an error, write a new post, etc.", we can use the same workflow to proof read new blog posts and it's much easier to maintain a nice (and consistent) site.

**Comment by beorn7** [comment]
+1 to shorter lines (just read up a bit about that, incidentally, when configuring the LaTeX Koma script for https://github.com/beorn7/midgard-szenarien ... :).

+1 to what @grobie said.

What I still want to know is if the blog part is meant for "news" style posts only, or also for "white paper" style posts (cf. the Golang blog). In case of the latter, where is the line between creating a new section in the proper docs area vs. a blog post? (I'm honestly confused about that in the case of the Golang blog. Some blog posts are really extensions of "effective Go" and pretty crucial/canonical.)

**Comment by brian-brazil** [comment]
I'm expecting the blog to be a mix of news, tutorials, whitepapers and general community stuff.

**Comment by juliusv** [comment]
I added a sidebar (which also makes the text column narrower) with links and the list of existing blog posts. The links section is just a straight copy of the ones @brian-brazil added to http://blog.prometheus.io/, so I'm happy to change anything in there. The posts section in the sidebar can be adjusted later to deal with a large number of articles (it should probably also be an archive selector like on http://blog.prometheus.io/).

blog_sidebar

**Comment by brian-brazil** [comment]
A few of the sidebar items are dupes with what the website already has, but otherwise :+1:

**Comment by juliusv** [comment]
Yeah, most of those links are reachable either via the top nav or other parts of the website already. Not sure if we care...

**Comment by brian-brazil** [comment]
I'd avoid the duplication. Maybe also put the word "Blog" in the navbar so it's obvious what you're looking at?

**Comment by fabxc** [comment]
Once there are a few posts, the sidebar can be filled with tag-links, i.e. #news, #tutorials...

**Comment by juliusv** [comment]
@fabxc Yes, planning to add some kind of tagging later. That can go into the sidebar then.

@brian-brazil I removed the links section for now, since it naturally contained mostly duplication. I renamed the "Posts" section to "Blog posts" to make it clearer that it's about blog posts...

blog_no_links

**Comment by juliusv** [comment]
Alright, if there are no more objections, I'll merge this tomorrow. Keep in mind the first version doesn't need to be perfect, happy to add things later as we start using the blog.

**Comment by juliusv** [comment]
Removed the top nav link and the test posts. Squashed. Merging...

**Pull request merged**
