### PR TITLE
Update link to Michael Stapelberg's German introduction talk

### PR DESCRIPTION
**Pull request by beorn7**
He gave a more up-to-date version of his previous talk at Easterhegg
2016. I think it makes more sense to link the newer talk here instead
of the old one.

@juliusv @stapelberg

### CODE REVIEW

**Comment by juliusv** [comment]
:+1:

**Comment by stapelberg** [comment]
Have you seen the Easterhegg talk? I’m not 100% sure if I represented everything correctly, so it might make sense to proof-watch it :).

**Comment by beorn7** [comment]
Yup, seen it. LGTM. Special shout-out for your "rrrr". :)

**Comment by stapelberg** [comment]
Perfect, glad to hear I didn’t screw things up :).

**Comment by juliusv** [comment]
@stapelberg Except that Alertmanager does support alert inhibitions (the question at the end) - but I commented that on the video ;)

**Comment by stapelberg** [comment]
Ah, good to know. Thanks for the clarification!

**Comment by grobie** [comment]
@juliusv Eh, I commented the same, I couldn't see your comment when I added it???

**Comment by juliusv** [comment]
:)

Btw., that makes me wonder whether we should link to the Youtube version (https://www.youtube.com/watch?v=uVcTviL7ar4) instead, since it enables commenting, and is also what people are more used to in general.

**Pull request merged**
