### PR TITLE
Test our blog

### PR DESCRIPTION
**Pull request by RichiH**
Signed-off-by: Richard Hartmann <richih@richih.org>

### CODE REVIEW

**Comment by RichiH** [comment]
Test failed successfully.

**Comment by RichiH** [comment]
@juliusv is this something we can make our blog do?

**Comment by roidelapluie** [comment]
did you try `<a>`

**Comment by roidelapluie** [comment]
not-as-easy-as it looks, does this propagate to RSS?

**Comment by juliusv** [comment]
I mean YAML frontmatter is decidedly not Markdown. But we could either encode some HTML in there (no idea what currently happens if you do that, if it's escaped or not), or we could have separate fields for author name and author URL, and then combine those in the output somehow.

**Comment by RichiH** [comment]
Works.

**Pull request closed without merging**
