### PR TITLE
Deleted leftover "e.g."

### PR DESCRIPTION
**Pull request by Mingan**
@juliusv

### CODE REVIEW

**Comment by beorn7** [comment]
I think the `e.g.` is fine here as the following sections is not only about names, but also about semantics of labels.

**Comment by Mingan** [comment]
You're right about that, but shouldn't `e.g.` link a concept and a list of instances of that concept?For example:

*Individual organizations may want to approach some of these practices, e.g. naming conventions, differently.*

**Comment by beorn7** [comment]
I leave it to @juliusv to decide as he might be into this kind of subtleties. ;)

**Comment by juliusv** [comment]
The current wording sounds correct to me, but you could maybe make it even clearer in the way you suggested, @Mingan.

**Comment by juliusv** [comment]
:+1: thanks!

**Pull request merged**
