### PR TITLE
Use Yaml indentation hints to avoid otherwise needless parentheses

### PR DESCRIPTION
**Pull request by beorn7**
As inspired by discussions of the alert mixin.

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'd considered this previously, however `|2` is not something I'd expect users to be aware of (I certainly wasn't until I dug through the YAML docs). Thus what we have is likely better in terms of understanding and maintainability.

**Comment by beorn7** [comment]
On the contrary, I think `|2` is really important for more readable rules, and thus we should spread the goodness.

**Comment by beorn7** [comment]
Speaking with the experience of shepherding 120 engineers using 50k lines of Prometheus rules files.

**Comment by beorn7** [comment]
I added an explicit hint so that the usage of `|2` doesn't go unnoticed.

**Comment by brian-brazil** [comment]
That could work. @juliusv what do you think?

**Comment by beorn7** [comment]
I have now linked the relevant section of the Yaml spec.

**Comment by juliusv** [comment]
I'm really unhappy with this whole issue with YAML as well :( I'm not sure which variant I find less bad. Maybe the one with the obscure indentation feature, but subsequent lack of paren requirements.

**Comment by beorn7** [comment]
While initially weird, it's not that hard to get used to `|2` (or whatever leading indentation you need). There was very little friction at SC once it was introduced.

**Comment by juliusv** [comment]
Ship it!

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
Thanks.

**Pull request merged**
