### PR TITLE
Added unofficial Clojure client library

### PR DESCRIPTION
**Pull request by jamtur01**

### CODE REVIEW

**Comment by brian-brazil** [comment]
We try to avoid duplicates in this list, and we already have one JVM client library.

**Comment by jamtur01** [comment]
I find most Clojure folks will use a wrapper over a native client library because it's more idiomatic. I don't see that as duplication.

**Comment by brian-brazil** [comment]
It's considered a duplication, and quickly looking at that library I'm not sure it's following the client library guidelines. 

Something that was actually a light wrapper or provided utilities for http would be fine (we list those elsewhere), this is some mix of wrapper and client library.

**Comment by jamtur01** [comment]
Okay.

**Pull request closed without merging**
