### PR TITLE
List unofficial Common Lisp client

### PR DESCRIPTION
**Pull request by deadtrickster**
https://github.com/deadtrickster/prometheus.cl

### CODE REVIEW

**Comment by SuperQ** [comment]
Nice :+1:

**Comment by juliusv** [comment]
Thanks! Please keep the alphabetic sorting :)

**Comment by deadtrickster** [comment]
@SuperQ thanks :-) 
@juliusv done!

**Comment by juliusv** [comment]
Thanks! :+1:

**Pull request merged**
