### PR TITLE
Document binary operator precedence.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@grobie @fabxc

**Comment by grobie** [comment]
:+1: Thanks!

**Comment by juliusv** [comment]
I added a sentence about left-associativity on the same level. @fabxc is that ok to expose in the specs, or better to leave undefined?

**Comment by fabxc** [comment]
Yes, that should be documented. I'd drop the "to change the order" part, though. In these cases it's usually easier to always use parentheses for explicitness.

:+1:

**Comment by juliusv** [comment]
Ok, I dropped the last sentence.

**Pull request merged**
