### PR TITLE
Replace CloudNativeCon news with PromCon

### PR DESCRIPTION
**Pull request by grobie**
@juliusv @brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
Would it make sense to feature the just-releated CloudNativeCon PrometheusDay videos for a couple of weeks first? @brian-brazil made a YouTube list: https://www.youtube.com/watch?list=PLqm7NmbgjUExeDZU8xb2nxz-ysnjuC2Mz

**Comment by RichiH** [comment]
It would.

Why not have both?

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

On Apr 3, 2017 22:46, "Julius Volz" <notifications@github.com> wrote:

Would it make sense to feature the just-releated CloudNativeCon
PrometheusDay videos for a couple of weeks first? @brian-brazil
<https://github.com/brian-brazil> made a YouTube list:
https://www.youtube.com/watch?list=PLqm7NmbgjUExeDZU8xb2nxz-ysnjuC2Mz

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/docs/pull/694#issuecomment-291268773>, or mute
the thread

**Comment by grobie** [comment]
I don't care, I already signed up for PromCon news ^^ I just wanted to
replace the outdated news.

**Comment by juliusv** [comment]
> Why not have both?

Banner real estate space.

I'd vote for having the CloudNativeCon vids there for two weeks or so, and then we can have a PromCon signup / register for notice link afterwards.

**Comment by grobie** [comment]
Or some fancy js to rotate through ;). Go ahead, I'll be offline the next 8
days.

**Comment by juliusv** [comment]
Cool. Here's my counter-suggestion that shows the CloudNativeCon Prometheus videos: https://github.com/prometheus/docs/pull/695

**Pull request closed without merging**
