### PR TITLE
Add Pretix to list of directly instrumented software

### PR DESCRIPTION
**Pull request by cherti**
Add ticketing-system Pretix to list of directly instrumented software.

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'll pull this into #749 in the exposing list, as this list is getting reorganised.

**Comment by cherti** [comment]
@brian-brazil shall I keep my branch around for reference for now?

**Comment by brian-brazil** [comment]
Keep it around, I won't get to changing my PR until the morning.

**Comment by cherti** [comment]
ok, will do!

**Pull request closed without merging**
