### PR TITLE
Fix typos across the docs repo.

### PR DESCRIPTION
**Pull request by ccamacho**
Fixed some blog and documentation typos.

### CODE REVIEW

**Comment by ccamacho** [comment]
Please, add the label Hacktoberfest to the pull request.

**Comment by juliusv** [comment]
Thanks! Hm, why the Hacktoberfest label? We don't have that label yet, and Hacktoberfest hasn't even started yet (it's September)... will they require that label on PRs? I'm only aware of tagging issues with a Hacktoberfest label.

**Comment by ccamacho** [comment]
Hey! You are right, no need for the label as that's on October, I forgot that from last year, but yeah they require the tag in PRs :)

**Comment by juliusv** [comment]
Just curious, once October comes: https://hacktoberfest.digitalocean.com/ doesn't mention anything about tagging PRs, just about tagging issues. Could you point me to something that mentions tagging the PRs too?

And merging this for now, thanks again!

**Pull request merged**
