### PR TITLE
Redirect www to apex domain using Netlify config

### PR DESCRIPTION
**Pull request by chalin**
This is an attempt at resolving

- #2208

without any further Netlify configuration changes.

/cc @juliusv

### CODE REVIEW

**Comment by chalin** [comment]
@juliusv, I'm not sure why the build is failing in this way:

```
5:02:31 PM: $ make downloads compile
5:02:31 PM: curl -sf -H 'Accept: application/vnd.github.v3+json' <GITHUB_AUTHENTICATION> https://api.github.com/repos/prometheus/prometheus > downloads/prometheus/repo.json
5:02:31 PM: make: *** [Makefile:22: downloads/prometheus/repo.json] Error 22
```

Any idea? When I build locally, it works fine. The `curl` is failing maybe because the `GITHUB_AUTHENTICATION` can't be accessed due to the new `netlify.config` file?

**Comment by juliusv** [comment]
Hi @chalin, yeah I think the reason would be the GitHub token, the Netlify build says:

```
11:02:14 PM: The following environment variables have been removed from this build to keep them secret:
11:02:14 PM: - GITHUB_AUTHENTICATION
```

Netlify omits secret env vars in builds triggered by non-team-members (because otherwise you could just extract them).

I just restarted the build myself in Netlify and now it seems to work. Of course we can't really test the apex domain redirect in the preview deployment anyway, so we just have to hope that it works.

However, we already have a bunch of Netlify redirects in https://github.com/prometheus/docs/blob/main/content/_redirects as well. Can we move this one in there as well, or is the `_redirects` file format not powerful enough for that?

**Comment by chalin** [comment]
Thanks for looking info the issue @juliusv.

> Can we move this one in there as well, or is the `_redirects` file format not powerful enough for that?

The convention we've been using is to separate redirect rules based on their role:

- We use  `_redirects` exclusively for intra-site redirect rules, whose purpose is to avoid 404s. This file is subject to more frequent updates, and tends to grow considerably over time.
- We put (sub)domain redirect rules (and other HTTP-response header config) in `netlify.toml`. This is a file that contributors should _very_ rarely be making changes to.

This separation helps to reduce the chance of inadvertent changes to the domain redirect rules, which might easily go unnoticed. Does that make sense?

**Comment by juliusv** [comment]
Thanks for the explanation, @chalin, that makes sense! I'll merge it and stick around to check that it's all working correctly once deployed.

**Pull request merged**
