### PR TITLE
Refactor download release selection

### PR DESCRIPTION
**Pull request by grobie**
* Add test
* Use Ruby's comparable module to implement sort behavior

Signed-off-by: Tobias Schmidt <tobidt@gmail.com>

---

Thanks for the fix @roidelapluie! I added a quick test so that the behavior can be migrated easily in case the docs page gets ported to hugo or such in the future.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Could you add v1.19.0-rc too, in the test?

**Comment by grobie** [comment]
@roidelapluie like this?

**Comment by roidelapluie** [comment]
Yes, but is -rc valid? or is it going to `rescue` and should be `-rc.0` ?

**Comment by grobie** [comment]
Semver defines a release candidate by "... a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]". So `-rc` is a valid pre-release identifier. I added an explicit `#version` test for that test case.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
