### PR TITLE
Add spacing to first row

### PR DESCRIPTION
**Pull request by ddavison**
Re-use the existing `top-hr` class which applies a margin to the first row.  

```css
.top-hr {
    margin-top: 30px;
}
```

### Before / After

prom

### CODE REVIEW

**Comment by ddavison** [comment]
> /cc @juliusv
> 
> I'm fighting with some GPG signing stuff, will get back to you.

:tada: This is ready now

**Comment by juliusv** [comment]
Thanks! We actually originally had a spacing in there by having a margin under the jumbotron (see https://web.archive.org/web/20160416134055/https://prometheus.io/), but it got removed when we inserted an intermediary header that had its own margin, and then we didn't think of adding it back when that intermediate header was removed. I was always wondering recently where that spacing went until I researched it now :) But the `top-hr` on the first row way also sounds good, thanks!

**Comment by juliusv** [comment]
@ddavison Oh, this added `top-tr`, but I guess it should've been `top-th`? (you'll see the site still looks the same :))

**Comment by juliusv** [comment]
It should be `top-hr` I mean of course, apparently that class name is hard to get right :laughing:

**Comment by ddavison** [comment]
Oh my goodness @juliusv You are absolutely right :facepalm:

**Comment by ddavison** [comment]
➡️ https://github.com/prometheus/docs/pull/1628

**Pull request merged**
