### PR TITLE
Update support-training.html

### PR DESCRIPTION
**Pull request by francjp**
Adding OpenNebula as part of the Commercial Support. Since https://github.com/prometheus/docs/pull/2330 hasn't been commented yet

Apologies in advance for insisting on this, but perhaps I followed the wrong path to request an addition on the Commercial Support. Is it possible to add OpenNebula as Commercial Support in Prometheus?

Please, if I'm not following the right procedure, let me know if I should do it in another way.

Best regards,

### CODE REVIEW

**Comment by RichiH** [comment]
The page lists service & support. While it seems that OpenNebula has Prometheus integrations, I couldn't find actual training & support as a primary offering. Could you point me to the right place, please?

**Comment by francjp** [comment]
> The page lists service & support. While it seems that OpenNebula has Prometheus integrations, I couldn't find actual training & support as a primary offering. Could you point me to the right place, please?

Hi @RichiH thanks for your reply.
We have Prometheus integrated on our Enterprise Edition (meaning commercial support included). You can find more information here:
- [Prometheus configuration on Frontend](https://docs.opennebula.io/6.6/management_and_operations/monitor_alert/install.html#step-4-configure-prometheus-front-end)
- [Monitor Alert](https://docs.opennebula.io/6.6/management_and_operations/monitor_alert/overview.html)
- [Release Notes 6.6](https://docs.opennebula.io/6.6/intro_release_notes/release_notes/whats_new.html#prometheus-grafana-ee)

Version 6.6 is the Enterprise edition. Let me know if this is good enough, or if you prefer to link the logo to a specific landing that clarifies this information.

Thanks!

**Comment by francjp** [comment]
Hello @RichiH any update on this?, do you need more information or links for our documentation?

Cheers,

**Comment by RichiH** [comment]
It would be better to have a page which clearly describes the services you provide, yes. NB: We normally require people to have Prometheus-specific support beyond simply hosting it. I wasn't 100% sure from looking at your links.

**Comment by francjp** [comment]
Hi @RichiH, sorry to insist on this, but have you had time to look on my last comment?. Is that enough, or do you think we should make any clarification on our page?

Best regards,

**Comment by francjp** [comment]
Hello @RichiH, it's me again. Do you have any update on this?, is it rejected or do you need more info on our side aside the webpage I linked above?: https://opennebula.io/subscriptions/#pricing_opennebula

Best regards,

**Comment by francjp** [comment]
Hello @RichiH and team, I'm still waiting an answer on this open PR. If we cannot be listed, can you clarify the reasons?

I'm seeing that other PR like this one: [Adding Cloudraft](https://github.com/prometheus/docs/pull/2344), was solved without any comment. 
As well as this one [Add Cloudwise](https://github.com/prometheus/docs/pull/2367), where I don't see much difference with what we explicitly said on our page about the support we give to Prometheus.

So I would like to check if it's a different criteria, or they have their support in a more explicit way than us.

cc @bwplotka @juliusv (I know that pinging people is not a good practice, but you are involved in the examples I'm pasting here).

In any case, thanks for any clarification you can give to me, to see if there's any solution to this PR.

**Comment by juliusv** [comment]
Hi @francjp thanks for pinging, and sorry for the long wait! It's true that we prefer as much Prometheus-specific information as possible, but also that we have not been strict about this as a requirement for others in the past, so I think it's ok enough as it is. At some point we may want to rethink the entire page since I'm not sure how useful it is now for potential customers. But for now it's ok.

However, we do want to keep the list alphabetically sorted, could you adjust that bit before I merge? Also, please do include the image file in the PR and link to it locally, as we want to be in control of the images we display on the Prometheus website.

**Comment by francjp** [comment]
Hi @juliusv thanks for your reply. I applied the changes requested, hoping everything is ok now. Let me know if you need more info, or if I have to make any other adjustment.

Cheers,

**Comment by juliusv** [comment]
@francjp thank you, it's still missing this part though:

> Also, please do include the image file in the PR and link to it locally, as we want to be in control of the images we display on the Prometheus website.

Could you also remove the unrelated extra empty line further down that was introduced in this PR?

**Review by francjp — COMMENTED** [review]
opennebula_cloud_logo_white_bg

Adding the logo locally

**Comment by francjp** [comment]
Hi @juliusv I cannot add the image locally on the folder "Assets", so I'm adding it here, I can change the URL, but it will be different to what you have on the file: https://github.com/prometheus/docs/assets/6509355/eae64100-da30-4ce3-80c4-05362a1d3c66

I'm probably missing something, so I'll appreciate any help.

**Comment by juliusv** [comment]
@francjp Ah yes, that's a bit confusing. Take a look at one of the other PRs for this page, for example: https://github.com/prometheus/docs/pull/2344/files - the file goes under `static/commercial-support-logos/` in the repo.

There's also still extra some trailing whitespace that's not related to the new logo, see https://github.com/prometheus/docs/pull/2331/files

**Review by francjp — COMMENTED** [review]
Removed Space and added logo locally

**Comment by juliusv** [comment]
@francjp Thanks, that looks good! The commit adding the logo is missing the `Signed-off-by: Francisco Picolini <fpicolini@opennebula.io>` line that you have on your other commits, which makes the DCO CI check fail - would you be able to add that (probably you'd have to interactively rebase, edit that one commit message, and then force push).

**Comment by francjp** [comment]
Hi @juliusv I rgot to sign my identity here (I used to have another email for github), so let me know if everything now looks good or I forgot something. Thanks a lot for your patience and your help.

Cheers

**Comment by juliusv** [comment]
@francjp Hmm, I still see the same thing as before - all commits have the DCO signoff, except for the one that adds the logo file. Compare for example https://github.com/prometheus/docs/pull/2331/commits/ce5f53f319468dd77388fd810d0f7577c0a1ce80 and https://github.com/prometheus/docs/pull/2331/commits/6f13ed2e2d4b95727faf538f75278c9cbaa679be.

**Review by francjp — COMMENTED** [review]
Updated and signed off

**Comment by juliusv** [comment]
@francjp Ah drat, I didn't see now(?) that the URL of the picture is still pointing at the remote version, not the local picture. And the trailing whitespace still seems to be there? I can merge this though for now (as the checks pass) and send a quick follow-up fix PR.

**Comment by francjp** [comment]
Thanks @juliusv and apologies for all the hassle. I don't know what happened, since I was following the procedure on signing a commit, so sorry again and many thanks for your help and patience.

**Comment by juliusv** [comment]
@francjp No worries, thanks for your patience with our CI gods as well :)

**Pull request merged**
