### PR TITLE
Introduce long term support

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>

### CODE REVIEW

**Comment by RichiH** [comment]
I like it.

I expect your new company to carry the workload, correct?

I would still suggest to discuss this during today's dev summit.

**Comment by roidelapluie** [comment]
So, the discussion happened in prevous dev summit: https://youtu.be/CtnpN-_KssY?t=4277 and in this design document: https://docs.google.com/document/d/1wCXLnvh460UG10Mw019UbYMWDwSWWdvgwY61LHY0A0w/edit and

**Comment by RichiH** [comment]
Wow, that's embarassing. I brainflushed on that.

**Comment by RichiH** [comment]
Should we still have a quick discussion if anyone has concerns about choosing this specific version?

**Review by RichiH — APPROVED** [review]
We just touched on it during the dev summit. No one has any concerns about version & timing.

Yay!

**Pull request merged**
