### PR TITLE
Adding checkbot to the list of exporters

### PR DESCRIPTION
**Pull request by tobiasdenzler**
@brian-brazil: Checkbot is able to run custom bash script in a container running on OpenShift. These scripts can check functionality and compliance settings in your cluster and will expose the result as Prometheus metrics.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. This seems pretty niche, there's other exporters out there that run scripts and both the pushgateway and node exporter can both take care of metrics from batch jobs.

**Comment by tobiasdenzler** [comment]
Might look like niche, but can be used for a variety of use cases. We apply this approach for compliance/security metrics on AWS services and Kafka management for example.

**Comment by brian-brazil** [comment]
We try to avoid duplication in this list, and this doesn't seem to be doing anything new plus it's restricted to openshift.

**Comment by tobiasdenzler** [comment]
Got it.. seems reasonable. Can you point me to the tools which provide similar functionality? Support for Kubernetes is on my list 😉

**Comment by brian-brazil** [comment]
In addition to the pushgateway and node exporter, there's the NRPE exporter and the various script exporters.

**Comment by tobiasdenzler** [comment]
I added support for Kubernetes and improved the documentation. I hope it is now clear which additional use cases checkbot can provide for monitoring. Otherwise feel free to close this PR.

**Comment by brian-brazil** [comment]
I'm afraid I'm still not seeing how this is usefully different compared to what's already listed, it can only work on some platforms and is inventing a new metrics format. You're free to announce it on the users list, but it doesn't seem to belong on this list.

**Pull request closed without merging**
