### PR TITLE
Operating: Document effects of higher GOGC values

### PR DESCRIPTION
**Pull request by beorn7**
To address https://github.com/prometheus/prometheus/issues/2665
@fabxc

### CODE REVIEW

**Comment by RichiH** [comment]
The new sentence seems tautologic.

**Comment by beorn7** [comment]
Just trying to be super clear here. Happy to leave it out if you all think it's obvious enough.

**Comment by RichiH** [comment]
What about:

If you need to conserve CPU capacity and can accept running with fewer memory chunks, try higher values.

**Comment by fabxc** [comment]
👍

**Comment by beorn7** [comment]
I like @RichiH 's suggestion. @fabxc is your thumb for my somewhat redundant version or for @RichiH 's more concise version?

**Comment by fabxc** [comment]
Clarification in general sounds good, Richi's suggestion too.

**Comment by RichiH** [comment]
I don't know how to edit this PR so see https://github.com/prometheus/docs/pull/731

**Pull request closed without merging**
