### PR TITLE
Adds fullstaq to commercial support

### PR DESCRIPTION
**Pull request by wiardvanrij**
Signed-off-by: Wiard van Rij <wiard@outlook.com>

Adds fullstaq to commercial support

### CODE REVIEW

**Comment by RichiH** [comment]
Can you sort yourself in alphabetically, please?

**Comment by RichiH** [comment]
Head's up: We may require a Prometheus-specific landing page listing specific services soonish, but that's not decided yet, and it would be unfair to block anyone from being merged in while that's not finalized.

**Comment by RichiH** [comment]
Thanks!

**Comment by wiardvanrij** [comment]
> Head's up: We may require a Prometheus-specific landing page listing specific services soonish, but that's not decided yet, and it would be unfair to block anyone from being merged in while that's not finalized.

Thanks, I will communicate this internally. 
Do you recon a more generic observability landing page would be fine as-well? We have no specific focus other than that it's cloud-native. So this could as-well be Thanos, Elastic, Loki, etc.

**Comment by RichiH** [comment]
No clear guidance yet, my gut is we will end up with "something focused on metrics", with PromCorThanos being the main projects to talk about.

**Pull request merged**
