### PR TITLE
Remove unnecessary indentation

### PR DESCRIPTION
**Pull request by lucperkins**
Just some basic code sample cleanup.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This indentation is correct, this is part of a much larger file.

**Comment by lucperkins** [comment]
I get that, but without the broader context of the `pom.xml` file it looks like an indentation error in the doc

**Comment by brian-brazil** [comment]
To be honest we should probably just remove that whole section. When it was added the per-lib docs weren't as good.

**Comment by lucperkins** [comment]
@brian-brazil That seems sensible. I've updated the PR.

**Pull request merged**
