### PR TITLE
Mention Loki along with ELK

### PR DESCRIPTION
**Pull request by dasJ**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we quote both, and can you please fix DCO? thanks

**Comment by RichiH** [comment]
I am biased, but only one does Prometheus-style labels for logs, no?

**Comment by roidelapluie** [comment]
> I am biased, but only one does Prometheus-style labels for logs, no?

Yes, that's why it is listed first. The other one is kinda the open source standard right now.

**Comment by roidelapluie** [comment]
What about we link to the CNCF landscape instead? https://landscape.cncf.io/category=logging&format=card-mode&grouping=category

**Comment by grobie** [comment]
> What about we link to the CNCF landscape instead?

Sounds like a great idea! "Don't! Use a [log aggregation system](https://landscape.cncf.io/category=logging&format=card-mode&grouping=category) instead."

**Comment by RichiH** [comment]
The landscape is confusing for users as evidenced again and again around
CNCF. I have asked TOC to address this several times, but to no avail.

Taking an opinionated stance seems better.

**Comment by roidelapluie** [comment]
I do not see anything wrong in the logging part of the landscape that is linked.

**Pull request closed without merging**
