### PR TITLE
Add trovilo to list of integrations

### PR DESCRIPTION
**Pull request by arnoldbechtoldt**
Signed-off-by: Arnold Bechtoldt <arnold.bechtoldt@inovex.de>

### CODE REVIEW

**Comment by arnoldbechtoldt** [comment]
Can I do something about the build status so we can get the PR in?

**Comment by lucperkins** [comment]
@arnoldbechtoldt Could you rebase with upstream/master and see if that helps?

**Comment by arnoldbechtoldt** [comment]
done! but the PR should be fully unrelated to that change, I think..

**Comment by arnoldbechtoldt** [comment]
So....?

**Comment by brian-brazil** [comment]
This tool isn't Prometheus specific, I'm not sure we should list this as it's more a k8 integration than a Prometheus one - just as we wouldn't list every possible configuration management tool like ansible, chef, etc.

**Comment by arnoldbechtoldt** [comment]
I don't agree, but I'm interested in that discussion.

**Pull request closed without merging**
