### PR TITLE
Added Julien to the Prometheus Maintainers Team.

### PR DESCRIPTION
**Pull request by bwplotka**
Welcome :tada: 

cc @roidelapluie 

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by RichiH** [comment]
I think it's more common to have the person themselves send the PR, but this also works.

**Comment by bwplotka** [comment]
> Team members are added to the list of team members in this document.

Yup, was not aware of this tradition, sorry ): We clarify this in the docs.

**Comment by bwplotka** [comment]
I still need some green tick, before merging (:

**Comment by bwplotka** [comment]
[](https://media2.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif)

**Pull request merged**
