### PR TITLE
Enforce utf-8 encoding on data sources

### PR DESCRIPTION
**Pull request by pracucci**
[Nanoc defaults to the current environment encoding](https://nanoc.ws/doc/troubleshooting/#wrong-input-encoding). If - for any reason - the default encoding is not `utf-8`, the compilation breaks with the following error:

```
Nanoc::DataSources::Filesystem::Errors::InvalidEncoding: Could not read repositories/prometheus.git/latest (2.10)/docs//storage.md because the file is not valid US-ASCII.
```

In this PR, I'm enforcing `utf-8` encoding on all data sources.

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can we set this in one place?

**Comment by pracucci** [comment]
> Can we set this in one place?

I'm not familiar with `nanoc`. I looked for it in the [`nanoc` doc](https://nanoc.ws/doc/data-sources/#configuration) and I haven't found any reference about a global setting (which I agree would be ideal).

**Comment by brian-brazil** [comment]
@grobie Do you know if there's one?

**Comment by pracucci** [comment]
I checked the source code:

- `nanoc` doesn't offer a way to globally set the `encoding` on the `Filesystem` data source (`RepoDocsDataSource` extends it)
- Ruby's `File.read()` infers the default encoding from the `LANG` environment variable

We may enforce it overriding the `LANG` env variable in the `Makefile`, but it's value may change on different systems (ie. `UTF-8` vs `C.UTF-8`). All in all, I would personally suggest to enforce it for each data source in the `nanoc.yaml` (this PR), but I'm open to suggestions and further discussion.

**Comment by grobie** [comment]
I'm unhappy about the current repo docs config structure anyway, it's too convoluted when tracking multiple versions. I'd hope to simplify that in a future version. For now, it's just one line more to copy&paste, I'd go forward with that.

**Comment by pracucci** [comment]
@brian-brazil Do you think there's interest into merging this PR?

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
