### PR TITLE
Update exporters.md

### PR DESCRIPTION
**Pull request by dl-romero**
Added Neptune Apex exporter
Signed-off-by: David Romero <dl_romero@outlook.com>

[sample_output.txt](https://github.com/user-attachments/files/16776263/sample_output.txt)

### CODE REVIEW

**Comment by juliusv** [comment]
Hi, thanks! I'd be happy to add it, the metrics just do seem deviating a bit too far from Prometheus best practices in some places, maybe it's possible to improve this?

* Was there a particular reason to not use the Python client library, which would also emit HELP and TYPE lines for metrics? Especially HELP lines would really help make sense of some of the metrics.
* I'm not sure exactly what `apex_sd_status_writes` for example means, but if it's a counter, then following Prometheus metric naming conventions, it should have a `_total` suffix (`apex_sd_status_writes_total`) to distinguish it from a possible gauge. See https://prometheus.io/docs/practices/naming/
* Ideally the different `apex_measurements` would be separate metric names since they measure different core aspects of the system, but if you don't know all of them beforehand and it's all auto-generated from whatever an API returns and has that extra `type` info on it, probably what you have is fine given the circumstances.
* Stuff like `alarm_description` and `module_values` really belongs into the HELP metadata line. If you make it part of the time series labels, not only will it pollute the output visually everywhere in the UI when you query for those metrics, but it will also create a whole new set of time series every time you change anything in those labels, since labels are identifying.

**Comment by dl-romero** [comment]
Hi, thank you for taking on this request.

For context, an Apex is hardware for marine water environment and chemical monitoring with automation capabilities. It is highly configurable and extendable with optional addons and sensor probes. 

In order here are my responses:

- There was no reason to not use the Python client library. This exporter originally intended for personal use, but after many requests for it in the marine keeping community, it was released publicly where I will be enhancing and maintaining. That said I am already refactoring to use the python client library.
- Using the python client, I will rename metrics accordingly using [best practices/naming](https://prometheus.io/docs/practices/naming/). The metric in question is in fact a counter. It's related to the write actions taken on an internal micro-sd card.
- Due to the Apex's extensibility. This is where it becomes difficult to know what the actual metric is and its unit of measurement. It could be probes to measure temperature, par, calcium, alkalinity, magnesium, nitrate, phosphate, copper, etc. For this metric I am pretty boxed into the current metric name with labels.
- Junk labels will be migrated to the HELP meta lines using the python client.

All of these changes are now currently planned to be rolled out in 2 weeks.

**Comment by juliusv** [comment]
@dl-romero Nice, thanks for the context, sounds good! Since you're planning on getting to the changes in the next weeks, let's wait with merging until then. Just let me know when :)

**Comment by dl-romero** [comment]
Hi @juliusv, before i push to prod, I wanted to share with you the new output. This should include all changes discussed so far. If all looks good to you Ill push to prod or I can continue making updates if any others are recommended.

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 1694.0
python_gc_objects_collected_total{generation="1"} 4344.0
python_gc_objects_collected_total{generation="2"} 144.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 169.0
python_gc_collections_total{generation="1"} 15.0
python_gc_collections_total{generation="2"} 1.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="11",patchlevel="5",version="3.11.5"} 1.0
# HELP sd_card_health Indicates SD Card Health Status
# TYPE sd_card_health gauge
sd_card_health 1.0
# HELP sd_card_read_error_total Total of SD Card Read Errors
# TYPE sd_card_read_error_total gauge
sd_card_read_error_total 0.0
# HELP sd_card_reads_total Total of SD Card Reads
# TYPE sd_card_reads_total gauge
sd_card_reads_total 6.418457e+06
# HELP sd_card_write_error_total Total of SD Card Write Errors
# TYPE sd_card_write_error_total gauge
sd_card_write_error_total 0.0
# HELP sd_card_writes_total Total of SD Card Writes
# TYPE sd_card_writes_total gauge
sd_card_writes_total 20200.0
# HELP measurement_log Measurement of Tmp.
# TYPE measurement_log gauge
measurement_log{did="base_Temp",log_source="apex",name="tmp"} 82.0
# HELP measurement_log Measurement of Ph.
# TYPE measurement_log gauge
measurement_log{did="base_pH",log_source="apex",name="ph"} 8.03
# HELP measurement_log Measurement of Alkalinity.
# TYPE measurement_log gauge
measurement_log{did="3_0",log_source="apex",name="alkalinity"} 8.76
# HELP measurement_log Measurement of Calcium.
# TYPE measurement_log gauge
measurement_log{did="3_1",log_source="apex",name="calcium"} 493.0
# HELP measurement_log Measurement of Magnesium.
# TYPE measurement_log gauge
measurement_log{did="3_2",log_source="apex",name="magnesium"} 1611.0
# HELP measurement_log Measurement of Sumphi.
# TYPE measurement_log gauge
measurement_log{did="1_I1",log_source="apex",name="sumphi"} 0.0
# HELP measurement_log Measurement of Swx1_2.
# TYPE measurement_log gauge
measurement_log{did="1_I2",log_source="apex",name="swx1_2"} 0.0
# HELP alarm_status Alarm Description: Alarm is off; Alarm_values: 0 = Off, 1 = On, 2 = metric issue
# TYPE alarm_status gauge
alarm_status 0.0
# HELP module_status Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_status gauge
module_status{module_port="1",module_type="FMM"} 1.0
# HELP module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_present gauge
module_present{module_port="1",module_type="FMM"} 1.0
# HELP module_status Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_status gauge
module_status{module_port="2",module_type="DQD"} 1.0
# HELP module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_present gauge
module_present{module_port="2",module_type="DQD"} 1.0
# HELP module_status Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_status gauge
module_status{module_port="3",module_type="TRI"} 1.0
# HELP module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE module_present gauge
module_present{module_port="3",module_type="TRI"} 1.0
# HELP network_quality_pct Network Quality in Percent
# TYPE network_quality_pct gauge
network_quality_pct 82.0
# HELP network_strength_pct Network Strength in Percent
# TYPE network_strength_pct gauge
network_strength_pct 100.0

**Comment by juliusv** [comment]
Thanks, looks much better already!

Two notes:

* We usually go for the plural in counters, so `sd_card_write_error_total` -> `sd_card_write_errors_total`
* I forgot to mention the second bullet point from https://prometheus.io/docs/practices/naming/ last time, but we usually also include an application/library-specific prefix in the metric names. That way when you see or type them into Prometheus or somewhere else, you immediately see which kind of exporter they are coming out of. Not sure what the right prefix would be here, something like `apex_` or `neptune_apex_`?

**Comment by dl-romero** [comment]
Got it. Here is another output after another update. This should include plural counters and pretext in naming.

```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 1694.0
python_gc_objects_collected_total{generation="1"} 4344.0
python_gc_objects_collected_total{generation="2"} 144.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 169.0
python_gc_collections_total{generation="1"} 15.0
python_gc_collections_total{generation="2"} 1.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="11",patchlevel="5",version="3.11.5"} 1.0
# HELP neptune_apex_sd_card_health Indicates SD Card Health Status
# TYPE neptune_apex_sd_card_health gauge
neptune_apex_sd_card_health 1.0
# HELP neptune_apex_sd_card_read_errors_total Total of SD Card Read Errors
# TYPE neptune_apex_sd_card_read_errors_total gauge
neptune_apex_sd_card_read_errors_total 0.0
# HELP neptune_apex_sd_card_reads_total Total of SD Card Reads
# TYPE neptune_apex_sd_card_reads_total gauge
neptune_apex_sd_card_reads_total 7.843097e+06
# HELP neptune_apex_sd_card_write_errors_total Total of SD Card Write Errors
# TYPE neptune_apex_sd_card_write_errors_total gauge
neptune_apex_sd_card_write_errors_total 0.0
# HELP neptune_apex_sd_card_writes_total Total of SD Card Writes
# TYPE neptune_apex_sd_card_writes_total gauge
neptune_apex_sd_card_writes_total 22067.0
# HELP neptune_apex_measurement_log Measurement of Tmp.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="base_Temp",log_source="apex",name="tmp"} 81.7
# HELP neptune_apex_measurement_log Measurement of Ph.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="base_pH",log_source="apex",name="ph"} 7.86
# HELP neptune_apex_measurement_log Measurement of Alkalinity.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="3_0",log_source="apex",name="alkalinity"} 8.56
# HELP neptune_apex_measurement_log Measurement of Calcium.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="3_1",log_source="apex",name="calcium"} 484.0
# HELP neptune_apex_measurement_log Measurement of Magnesium.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="3_2",log_source="apex",name="magnesium"} 1614.0
# HELP neptune_apex_measurement_log Measurement of Sumphi.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="1_I1",log_source="apex",name="sumphi"} 0.0
# HELP neptune_apex_measurement_log Measurement of Swx1_2.
# TYPE neptune_apex_measurement_log gauge
neptune_apex_measurement_log{did="1_I2",log_source="apex",name="swx1_2"} 0.0
# HELP neptune_apex_alarm_status Alarm Description: Alarm is off; Alarm_values: 0 = Off, 1 = On, 2 = metric issue
# TYPE neptune_apex_alarm_status gauge
neptune_apex_alarm_status 0.0
# HELP neptune_apex_module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE neptune_apex_module_present gauge
neptune_apex_module_present{module_port="1",module_type="FMM"} 1.0
# HELP neptune_apex_module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE neptune_apex_module_present gauge
neptune_apex_module_present{module_port="2",module_type="DQD"} 1.0
# HELP neptune_apex_module_present Status for Connected Module. 0 = Not Ok/False, 1 = Ok/True, 2 = metric issue
# TYPE neptune_apex_module_present gauge
neptune_apex_module_present{module_port="3",module_type="TRI"} 1.0
# HELP neptune_apex_network_quality_pct Network Quality in Percent
# TYPE neptune_apex_network_quality_pct gauge
neptune_apex_network_quality_pct 84.0
# HELP neptune_apex_network_strength_pct Network Strength in Percent
# TYPE neptune_apex_network_strength_pct gauge
neptune_apex_network_strength_pct 100.0
```

**Comment by juliusv** [comment]
Nice, thanks! 😊👍

**Pull request merged**
