### PR TITLE
Use draw.io for architecture diagram

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Awesome, thanks!

Is it intentional that the new one has serif fonts, while the old one was completely sans serif? I don't have a big opinion either way.

**Comment by lucperkins** [comment]
@juliusv Hmmm. I'm not really seeing any serif fonts. The *file_sd* in the Service Discovery block is monospaced because that's code, but besides that everything is in the Lato font to match the docs.

**Comment by juliusv** [comment]
@lucperkins Huh weird, it looks like this to me in GitHub and also when I import the XML into draw.io:

serifs

Maybe just my browser though. Merging to see what it'll look like on the final site :)

**Comment by juliusv** [comment]
Hmm, now it's on the live site and still has serifs for me, while the old one was perfectly sans-serifed.

Oh well, maybe some explicit font stuff is missing, but it's getting late here. Might look into it myself soon since now we have the XML source and a free tool - thanks! :)

**Comment by lucperkins** [comment]
@juliusv **Sigh**. It looks like it depends which fonts are available on the reader's machine (rather than being embedded within the SVG itself). I'll see if draw.io has different export options.

**Pull request merged**
