### PR TITLE
[exporters] File statistics exporter

### PR DESCRIPTION
**Pull request by michael-doubez**
Simple exporter to gather simple metrics about files.

### CODE REVIEW

**Comment by SuperQ** [comment]
Neat, one metric naming suggestion, `file_glob_match_number` becomes `file_glob_matches`.

**Comment by SuperQ** [comment]
Please fix the DCO with `git commit -s --amend`

**Comment by michael-doubez** [comment]
> Please fix the DCO with `git commit -s --amend`

Done

**Comment by michael-doubez** [comment]
> Neat, one metric naming suggestion, `file_glob_match_number` becomes `file_glob_matches`.

Is there any rule of thumb for gauges as there is `_total` for counters ?

**Comment by michael-doubez** [comment]
Should I still hope for integration ?
Note: Debian package exists https://packages.debian.org/source/sid/prometheus-exporter-exporter

**Comment by juliusv** [comment]
Thanks, I think this just got lost in time, merging it now.

> Is there any rule of thumb for gauges as there is _total for counters (mandatory in OpenMetrics IIRC) ?

There's no explicit suffix convention for gauges, so instead of `_number`, one generally just uses the plural of whatever is being tallied / measured, and that's it.

**Pull request merged**
