### PR TITLE
Fix typo & PostgreSQL stying in Sensu comparison

### PR DESCRIPTION
**Pull request by bananabele**
Trying this again -- fixing the spelling of "multiple" and PostgreSQL in the Sensu comparison section

### CODE REVIEW

**Comment by brian-brazil** [comment]
I think you need to squash that, https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git should help.

**Comment by bananabele** [comment]
Thanks @brian-brazil! I spent a bit more time on it this morning and still can't get it to work. this is stretching beyond my very limited git knowledge; at this point, I'd be happy to delete this PR too and let someone else fix the typo.

**Comment by brian-brazil** [comment]
The main thing is you've pulled in a whole pile of unrelated commits. Try `git reset --hard e2f6a7d` and then `rebase -i` from there. Don't run a merge or pull.

**Comment by bananabele** [comment]
Closing to restart fresh. Third time's a charm!

**Pull request closed without merging**
