### PR TITLE
Add huawei cloudeye exporter

### PR DESCRIPTION
**Pull request by zhongjun2**
Signed-off-by: zhongjun2 <jun.zhongjun2@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

The metric name prefix should not be configurable, and I'd also advise against munging of label names.

**Comment by zhongjun2** [comment]
Thanks brian-brazil!  " I'd also advise against munging of label names. " ----- Where I can find what label I can use, what label I can not use? Is there a link or something else?

**Comment by brian-brazil** [comment]
I'm looking at https://github.com/huaweicloud/cloudeye-exporter/blob/master/collector/collector.go#L30

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels are the docs, if there are invalid characters you'd usually change them to underscores.

**Comment by zhongjun2** [comment]
Got it, thanks brian-brazil!

**Pull request merged**
