### PR TITLE
Added Consul Telemetry Exporter

### PR DESCRIPTION
**Pull request by lchayoun**

### CODE REVIEW

**Comment by brian-brazil** [comment]
We already have an exporter for consul metrics, and we try to avoid duplicates in this list. Have you talked to the maintainer of it about adding any metrics it is currently missing?

@grobie

**Comment by lchayoun** [comment]
hi @brian-brazil 
The metrics are different than the ConsulExporter metrics
The ConsulExporter is providing metrics about the consul data while this exporter provide the metrics of consul internal state
currently the metrics are provided using statsd, this will provide a simpler exporter that doesn't require any other middleware

**Comment by ezraroi** [comment]
Hi @brian-brazil, consul exporter is exporting the catalog and health checks from the consul cluster. You must run 1 consul exporter for the consul cluster. This new exporter is exporting consul server / agent telemetry and you should run the new exporter for every instance of the consul cluster

**Comment by lchayoun** [comment]
@brian-brazil any update on this?

**Comment by brian-brazil** [comment]
This duplicates functionallity that would belong in the consul_exporter, and in fact I've a PR out to add it.

**Pull request closed without merging**
