### PR TITLE
Added Dockerized Version of Gotify

### PR DESCRIPTION
**Pull request by ndragon798**
Added Dockerized Version of Gotify

Signed-off-by: Nathan Easton <nathaneaston@nathaneaston.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. This would make sense to add to the Gotify repository rather than here.

**Comment by ndragon798** [comment]
I did make a pr there but there hasn't been activity on the repo in a couple of months.

**Comment by brian-brazil** [comment]
There's not much I can do to help you there I'm afraid. If a successor repository appears we can change the listing, but it is not my place to point to unofficial builds of exporters.

**Comment by ndragon798** [comment]
Got in contact with the author of the bridge and got my dockerized version added to the readme.

**Comment by brian-brazil** [comment]
Great!

**Pull request closed without merging**
