### PR TITLE
exporters.md: Add knxd_exporter

### PR DESCRIPTION
**Pull request by RichiH**

### CODE REVIEW

**Comment by RichiH** [comment]
Now with brains!

**Comment by brian-brazil** [comment]
Thanks, this would probably fit better as a http server.

**Comment by RichiH** [comment]
On Wed, Jan 27, 2016 at 10:45 PM, Brian Brazil <notifications@github.com> wrote:

> Thanks, this would probably fit better as a http server.

I know; this is shoddy, but it works. I plan to improve it over time
and might get around to implementing basic HTTP for this and other
exporters.


Richard

**Comment by grobie** [comment]
Looks actually like a great candidate for the textfile collector of the
node_exporter.

**Comment by brian-brazil** [comment]
Knxd can also work over IP (not just USB), so that implies it should to be an exporter.

**Comment by brian-brazil** [comment]
http://www.robustperception.io/writing-a-jenkins-exporter-in-python/ should be a good starting point.

**Pull request merged**
