### PR TITLE
Add a shortcut for /storage

### PR DESCRIPTION
**Pull request by roidelapluie**
to merge before https://github.com/prometheus/prometheus/pull/7691

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by RichiH** [comment]
Should this go to `/nfs` or even `/go/nfs`?

**Comment by roidelapluie** [comment]
> Should this go to `/nfs` or even `/go/nfs`?

While now it is for NFS it could be extended in the future, WDYT? I have no strong opinion about the /go part.

**Comment by brian-brazil** [comment]
I don't think we should start creating a redirect farm, let's just link to the doc page directly.

**Comment by roidelapluie** [comment]
It is short. If an operator sees this on a vnc or bmc, without copy/paste, they can quickly type the link in a browser.

I also anticipate that we would need a redirect anyway when the docs would move and need a redirect. As people use old version of prometheus, that link will be around for a long time.

**Comment by brian-brazil** [comment]
As-is searching for "prometheus nfs" will find it, I don't feel we should be over-thinking this.

**Pull request closed without merging**
