### PR TITLE
Add dev summit 2021-02

### PR DESCRIPTION
**Pull request by RichiH**
Signed-off-by: Richard Hartmann <richih@richih.org>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Why didn't you link the existing public calendar instead?

**Comment by roidelapluie** [comment]
https://calendar.google.com/calendar/embed?src=prometheus.io_bdf9qgm081nrd0fe32g3olsld0%40group.calendar.google.com&ctz=Europe%2FParis

**Comment by RichiH** [comment]
I did, just without trailing time zone?

**Comment by RichiH** [comment]
Wait, something weird going on. There seem to be two calendars. Will need to fix that before merging.

**Comment by roidelapluie** [comment]
There is a Prometheus Public Calendar which we feed with Storage WG and contributor hours.

**Comment by RichiH** [comment]
I can not find it in the Prometheus.io GSuite. Is that cal enabled for everyone with an @prometheus.io account?

**Comment by roidelapluie** [comment]
Yes

**Comment by metalmatze** [comment]
I was just on https://prometheus.io/community/ looking for a calendar link. This would be super helpful. Not sure how I can help but let me know.

**Comment by beorn7** [comment]
https://github.com/prometheus/docs/pull/1898

@RichiH just click on that link, and the calendar will be added to your personal calendar list.

**Comment by RichiH** [comment]
See https://github.com/prometheus/docs/pull/1900

**Pull request closed without merging**
