### PR TITLE
add MOIA to the list of Prometheus users

### PR DESCRIPTION
**Pull request by guusvw**
Signed-off-by: Guus van Weelden <guus.vanweelden@moia.io>

cc @brian-brazil @juliusv

### CODE REVIEW

**Comment by guusvw** [comment]
Is failing because of 

```
1:04:05 PM: make: *** [downloads/blackbox_exporter/repo.json] Error 22
1:04:05 PM: Skipping functions preparation step: no functions directory set
```

😅

**Comment by juliusv** [comment]
Seemed like a transient CI failure, restarted the CI build.

**Comment by juliusv** [comment]
:+1: Thanks

(btw. there's been talk of removing this users list altogether in favor of a smaller list of case studies somewhere else on the site, so this might not be around forever)

**Comment by guusvw** [comment]
@juliusv feel free to ping me if you convert to case studies, I think https://github.com/moia-dev/ have some interesting use cases ;) 🚌

**Comment by juliusv** [comment]
@guusvw Thanks, sounds good :)

**Pull request merged**
