### PR TITLE
Add new IPsec exporter to exporters list

### PR DESCRIPTION
**Pull request by torilabs**
Sample output:
```
# HELP strongswan_ike_reauth_seconds Seconds until the IKE will be reauthed
# TYPE strongswan_ike_reauth_seconds gauge
strongswan_ike_reauth_seconds{ike_id="some-unique-id",ike_name="ike-name"} 15
```

### CODE REVIEW

**Comment by juliusv** [comment]
@torilabs Thanks! Could you share a more extensive sample output? I see so many more metrics than just one here: https://github.com/torilabs/ipsec-prometheus-exporter/blob/master/strongswan/collector.go

Some general comments from just glancing at the list:

* For all the "Seconds since..." metrics, would it be possible to expose a timestamp instead? That's a more common pattern in Prometheus, and then you can calculate the age of the timestamp in PromQL (`time() - my_timestamp_seconds`).
* For metrics like `strongswan_sa_outbound_bytes` that represent counters, the usual naming convention would be to add a `_total` prefix to clarify that they are not a gauge (and also expose the type as counter, not gauge). See also https://prometheus.io/docs/practices/naming/#metric-names.

**Comment by torilabs** [comment]
Hi @juliusv 
> * For all the "Seconds since..." metrics, would it be possible to expose a timestamp instead? That's a more common pattern in Prometheus, and then you can calculate the age of the timestamp in PromQL (`time() - my_timestamp_seconds`).

Actually not. The value is directly taken from VICI API of IPsec StrongSwan and I don't want to modify it. Just report what is exposed by the API. Additionally using raw value (as it is reported) is much suitable for related alerting.

> * For metrics like `strongswan_sa_outbound_bytes` that represent counters, the usual naming convention would be to add a `_total` prefix to clarify that they are not a gauge (and also expose the type as counter, not gauge). See also https://prometheus.io/docs/practices/naming/#metric-names.

The counters are quite tricky in this case as I'm receiving value from VICI API and I'm not sure what value was the previous reported one. I can not be sure the next value is greater or equal compared to the previous one. That is also why we stayed with just `_bytes` suffix instead of `_bytes_total`. This was discussed with some other DEV engineers and operations guys within the team.

Some more metrics:
```
# HELP strongswan_ike_children_size Count of children of this IKE
# TYPE strongswan_ike_children_size gauge
strongswan_ike_children_size{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_count Number of known IKEs
# TYPE strongswan_ike_count gauge
strongswan_ike_count 1
# HELP strongswan_ike_encryption_key_size Key size of the encryption algorithm
# TYPE strongswan_ike_encryption_key_size gauge
strongswan_ike_encryption_key_size{algorithm="",dh_group="",ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_established_seconds Seconds since the IKE was established
# TYPE strongswan_ike_established_seconds gauge
strongswan_ike_established_seconds{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_initiator Flag if the server is the initiator for this connection
# TYPE strongswan_ike_initiator gauge
strongswan_ike_initiator{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_integrity_key_size Key size of the integrity algorithm
# TYPE strongswan_ike_integrity_key_size gauge
strongswan_ike_integrity_key_size{algorithm="",dh_group="",ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_nat_any Flag if any endpoint is behind a NAT (also if faked)
# TYPE strongswan_ike_nat_any gauge
strongswan_ike_nat_any{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_nat_fake Flag if NAT situation has been faked as responder
# TYPE strongswan_ike_nat_fake gauge
strongswan_ike_nat_fake{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_nat_local Flag if the local endpoint is behind nat
# TYPE strongswan_ike_nat_local gauge
strongswan_ike_nat_local{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_nat_remote Flag if the remote server is behind nat
# TYPE strongswan_ike_nat_remote gauge
strongswan_ike_nat_remote{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_reauth_seconds Seconds until the IKE will be reauthed
# TYPE strongswan_ike_reauth_seconds gauge
strongswan_ike_reauth_seconds{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_rekey_seconds Seconds until the IKE will be rekeyed
# TYPE strongswan_ike_rekey_seconds gauge
strongswan_ike_rekey_seconds{ike_id="some-unique-id",ike_name="ike-name"} 0
# HELP strongswan_ike_status Status of this IKE
# TYPE strongswan_ike_status gauge
strongswan_ike_status{ike_id="some-unique-id",ike_name="ike-name"} 2
# HELP strongswan_ike_version Version of this IKE
# TYPE strongswan_ike_version gauge
strongswan_ike_version{ike_id="some-unique-id",ike_name="ike-name"} 5
```

**Comment by juliusv** [comment]
Thanks for the explanations! Yeah, I just wanted to highlight those in case it hadn't come up. Happy to merge if it has been considered.

> I can not be sure the next value is greater or equal compared to the previous one.

Are those just occasional counter resets (which are ok to have in counter metrics), or is there some other phenomenon which causes them to be lower? Just wondering what the actual semantics of these metrics is, or if they have any meaning at all.

**Comment by torilabs** [comment]
> Are those just occasional counter resets (which are ok to have in counter metrics), or is there some other phenomenon which causes them to be lower? Just wondering what the actual semantics of these metrics is, or if they have any meaning at all.
Metrics resets are expected but when monitoring "remote" service/container there is some kind of uncertainty. In the future we can prove how the values behave and update (major version change).

**Comment by torilabs** [comment]
@RichiH can I ask you to approve and merge this PR please

**Pull request merged**
