### PR TITLE
Add alertmanager-gotify-bridge project to integrations

### PR DESCRIPTION
**Pull request by DRuggeri**
Add another webhook receiver for alertmanager integrations

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. This takes a secret on the command line, which is not secure. Can you fix that please, and then we can list it?

**Comment by DRuggeri** [comment]
Ah, yes, that's right. I've fixed that now in https://github.com/DRuggeri/alertmanager_gotify_bridge/commit/18914ae2ab79504f7d21f351684e82d8216ab397

**Comment by DRuggeri** [comment]
Good to merge?

**Comment by brian-brazil** [comment]
Thanks!

The readme makes it seem as though the flag would work, which is a bit confusing.

**Comment by DRuggeri** [comment]
Oops - thanks, @brian-brazil. Fixed that in the README just now.

**Pull request merged**
