### PR TITLE
Add Diffusion to third-party software list.

### PR DESCRIPTION
**Pull request by philipa**
@brian-brazil 

Diffusion is a commercial software product from Push Technology.

### CODE REVIEW

**Comment by brian-brazil** [comment]
That URL isn't right, and I think https://developers.pushtechnology.com/hc/en-us/articles/360034215494-How-To-Use-Metric-Collectors would be more useful.

You don't appear to actually document how to get the metrics. I presume "gateway" doesn't mean the pushgateway, I can imagine that confusing some of your users so would suggest clarifying.

**Comment by philipa** [comment]
Thanks Brian; yes I agree. The blog you found is about general configuration of Diffusion's metric collection and not specific to Prometheus.

I've updated the URL to point to the relevant page in our manual.

**Comment by brian-brazil** [comment]
Thanks!

diffusion_sessions_peak sounds like a gauge rather than a counter. Counters should also generally end in _total (except if part of a Summary/Histogram), and _count should be for that series in a Summary/Histogram.

**Comment by philipa** [comment]
`diffusion_sessions_peak` can only go up. It is the highest number of sessions the server has ever hosted (it is the maximum value of `diffusion_sessions_open`). There is a separate `diffusion_sessions_total` metric

**Comment by brian-brazil** [comment]
That's still a Gauge. You care about the absolute value, not how fast it is going up.

**Comment by philipa** [comment]
Since `_peak` is monotonically increasing, isn't a counter appropriate? What benefit would using a gauge bring?

**Comment by brian-brazil** [comment]
Counters always go up, but that doesn't mean that everything that always goes up is a counter. Counters are not meant to be usable without using rate() first, whereas diffusion_sessions_peak is usable as-is.

**Comment by SuperQ** [comment]
@philipa Even tho it's monotonically increasing, it's not counting anything.

**Comment by philipa** [comment]
OK, schooled! I'll get this fixed. Thanks for your patience.

**Pull request merged**
