### PR TITLE
Add Ballerina to the homepage of prometheus

### PR DESCRIPTION
**Pull request by chrishantha**
[Ballerina](https://ballerina.io/) is a programming language for integration. Ballerina services are by default [observable](https://ballerina.io/learn/how-to-observe-ballerina-code/) and it supports Prometheus. Ballerina run-time will start an HTTP endpoint for Prometheus to scrape metrics when observability is enabled.

We would like to be featured in Prometheus homepage as a Prometheus user.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is a list of companies using Prometheus, so I think you want to add WSO2 here.

**Comment by DSotnikov** [comment]
While WSO2 is one of the biggest contributors of Ballerina, [Ballerina remains an open source project with non-WSO2 contributors as well](https://github.com/ballerina-platform/ballerina-lang), so imho it makes more sense to list Ballerina and not WSO2 there.

**Comment by brian-brazil** [comment]
Integrations go elsewhere on the website if you want to add it there, this is a list of companies using Prometheus.

**Comment by DSotnikov** [comment]
Got it. @chrishantha simply submitted the change to the wrong place.

I guess https://prometheus.io/docs/instrumenting/clientlibs/ and https://prometheus.io/docs/instrumenting/exporters/ would be better places.

**Comment by chrishantha** [comment]
@DSotnikov Yes, I have put Ballerina in the wrong place. I first assumed that all logos are Prometheus users (not just companies using Prometheus). I think the correct place for Ballerina is to be in https://prometheus.io/docs/instrumenting/exporters/ under "[Software exposing Prometheus metrics](https://prometheus.io/docs/instrumenting/exporters/#software-exposing-prometheus-metrics)"

@brian-brazil I will send new changes.

**Comment by chrishantha** [comment]
Hi @brian-brazil,

I sent a new PR  #1061. Please review. I tested the website by following the instructions in README.

**Pull request closed without merging**
