### PR TITLE
Add Splunk(read and write) to list of remote storages

### PR DESCRIPTION
**Pull request by kebe7jun**
Ropee is a prometheus remote storage adapter for splunk designed by @DaoCloud.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for sharing. It looks like this is a superset of the currently listed one, so you can replace it.

Your README has a password on the commandline, can you move it somewhere more secure?

There's also no need for read_recent to be true.

**Comment by kebe7jun** [comment]
Thanks for your comment, I have updated my [repo's README](https://github.com/kebe7jun/ropee) and removed old Splunk adaptor.

**Comment by brian-brazil** [comment]
You're still taking a password on the command line, both in the docker example and the adapter itself.

**Comment by kebe7jun** [comment]
> You're still taking a password on the command line, both in the docker example and the adapter itself.

@brian-brazil 
I have removed the auth from command line for secure. 
https://github.com/kebe7jun/ropee#configuring-prometheus

**Comment by brian-brazil** [comment]
I still see it in the code: https://github.com/kebe7jun/ropee/blob/master/main.go#L67

We ask that there's no obvious security issues before listing something here, which basically means not exposing passwords on the command line.

**Comment by kebe7jun** [comment]
Sorry about that, I have removed the password option from command.
commit: https://github.com/kebe7jun/ropee/commit/5ae55ed39a4d977e67c4e073426318e487ded09e

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
