### PR TITLE
Add artifactory_exportter to misc exporters

### PR DESCRIPTION
**Pull request by peimanja**
Here I want to add our [JFrog Artifactory Exporter](https://github.com/peimanja/artifactory_exporter) to list of Miscellaneous exporters.

Here are example of exported metrics and we are planning to work on extending this exporter in the future:
```
# HELP arti_artifacts_total_count Total artifacts count stored in Artifactory
# TYPE arti_artifacts_total_count gauge
arti_artifacts_total_count 24648
# HELP arti_artifacts_total_size_bytes Total artifacts Size stored in Artifactory in bytes
# TYPE arti_artifacts_total_size_bytes gauge
arti_artifacts_total_size_bytes 2.455647551488e+11
# HELP arti_binaries_total_count Total binaries count stored in Artifactory
# TYPE arti_binaries_total_count gauge
arti_binaries_total_count 19887
# HELP arti_binaries_total_size_bytes Total binaries Size stored in Artifactory in bytes
# TYPE arti_binaries_total_size_bytes gauge
arti_binaries_total_size_bytes 1.588064157696e+11
# HELP arti_filestore_bytes Total space in the file store in bytes
# TYPE arti_filestore_bytes gauge
arti_filestore_bytes{storage_dir="/var/opt/jfrog/artifactory-ha/cache",storage_type="cluster-s3"} 9.223372036854776e+18
# HELP arti_filestore_free_bytes Space free in the file store in bytes
# TYPE arti_filestore_free_bytes gauge
arti_filestore_free_bytes{storage_dir="/var/opt/jfrog/artifactory-ha/cache",storage_type="cluster-s3"} 9.223371708100799e+18
# HELP arti_filestore_used_bytes Space used in the file store in bytes
# TYPE arti_filestore_used_bytes gauge
arti_filestore_used_bytes{storage_dir="/var/opt/jfrog/artifactory-ha/cache",storage_type="cluster-s3"} 3.3236604420096e+11
# HELP arti_repo_files_count Number files in an Artifactory repository
# TYPE arti_repo_files_count gauge
arti_repo_files_count{name="artifactory-build-info",package_type="buildinfo",type="local"} 5623
# HELP arti_repo_folder_count Number of folders in an Artifactory repository
# TYPE arti_repo_folder_count gauge
arti_repo_folder_count{name="artifactory-build-info",package_type="buildinfo",type="local"} 301
# HELP arti_repo_items_count Number Items in an Artifactory repository
# TYPE arti_repo_items_count gauge
arti_repo_items_count{name="artifactory-build-info",package_type="buildinfo",type="local"} 5924
# HELP arti_repo_percentage Percentage of space used by an Artifactory repository
# TYPE arti_repo_percentage gauge
arti_repo_percentage{name="artifactory-build-info",package_type="buildinfo",type="local"} 0.01
# HELP arti_repo_used_bytes Space used by an Artifactory repository in bytes
# TYPE arti_repo_used_bytes gauge
arti_repo_used_bytes{name="artifactory-build-info",package_type="buildinfo",type="local"} 1.938817024e+07
# HELP arti_security_users Number of artifactory users
# TYPE arti_security_users gauge
arti_security_users{realm="internal"} 36
arti_security_users{realm="saml"} 56
# HELP arti_up Current health status of the server (1 = UP, 0 = DOWN)
# TYPE arti_up gauge
arti_up 1
```

### CODE REVIEW

**Comment by peimanja** [comment]
Figured it is not mature enough. Closing for now.

**Comment by brian-brazil** [comment]
Maturity isn't a hard requirement, as long as it basically works it can improve over time. Taking a password on the command line is a problem however.

You should collect data on scrape, not on a timer. Relatadely your handling of an up variable isn't correct, you want it to be 0 if there's any failure - not just if the initial connection fails. I'd suggest failing the entire scrape here rather than having an up.

`prom_request_time` is also not a good metric name as that would indicate it's a metric from Prometheus code rather than your code. I'd suggest dropping it and leaving it to `scrape_time_seconds` on the Prometheus side. I'd also go with `artifactory_` for clarity.

`arti_artifacts_total_count` - gauges should not end in either _total or _count. `arti_repo_percentage` is redundant, you can calculate it from other metrics.

**Comment by peimanja** [comment]
@brian-brazil Alrighty! Thanks for great feedback. Made me go back and read documentation again and refactor the code to address your comments. Now it is in much better shape. Would be great if we get it added in the list

**Comment by brian-brazil** [comment]
You've still a password on the command line in your readme.

**Comment by peimanja** [comment]
> You've still a password on the command line in your readme.

Password is now only can be set via environment variables which depends on how the user run containers or the application itself but now the password is removed from the command line flags.

If your point is to not encourage people to set the environment variable that way, sure I can adjust it in the readme.

**Comment by brian-brazil** [comment]
Yeah, passwords should never be in argv - even briefly.

**Comment by peimanja** [comment]
> Yeah, passwords should never be in argv - even briefly.

Fair enough. Modified the readme.

**Comment by brian-brazil** [comment]
Thanks!

"run the artifactory exporter as a Docker container, run" is a little awkward.

**Pull request merged**
