### PR TITLE
Add ThousandEyes exporter

### PR DESCRIPTION
**Pull request by vonneudeck**
Exports alerts from ThousandEyes.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?

**Comment by beorn7** [comment]
@vonneudeck as @brian-brazil said, could you [add the DCO](https://github.com/prometheus/docs/pull/1314/checks?check_run_id=88458155)?

**Comment by vonneudeck** [comment]
Thanks for waiting so long Brian. And thanks for reminding me again Björn. I owe both of you a lemonade.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
