### PR TITLE
Change DO logo from png to svg

### PR DESCRIPTION
**Pull request by RichiH**
As per https://github.com/prometheus/docs/pull/2351#issuecomment-1635619390

### CODE REVIEW

**Comment by RichiH** [comment]
@juliusv same behaviour as before. Could you help with sizing the SVG, please?

**Comment by RichiH** [comment]
@juliusv that works, thanks. Are you particular about 250px? I think the 200 looked better. Alternatively, the CNCF logo is 300 wide, so we can make them the same.

**Comment by RichiH** [comment]
NB: The whole text width is a clickable link for both CNCF & DO, which is not HTML default behaviour -- but I don't think it's worth digging to find what causes this.

**Comment by juliusv** [comment]
> Are you particular about 250px? I think the 200 looked better.

Either is fine :+1: 

> The whole text width is a clickable link for both CNCF & DO

That's because we have a CSS rule that sets doc content images to `display: block`, but fine with me.

:+1:

**Pull request merged**
