### PR TITLE
Fix-typo-sensu-comparison

### PR DESCRIPTION
**Pull request by bananabele**
Fixing a small typo in the second bullet of "where Sensu is better" (mulitple => multiple)

### CODE REVIEW

**Comment by bananabele** [comment]
tagging @juliusv for review 👀

**Comment by brian-brazil** [comment]
Can you add the DCO?

**Comment by roidelapluie** [comment]
While you are at it, woulnd't it be better to change Postgres to PostgreSQL ?

**Comment by bananabele** [comment]
I'm sorry, I'm making it so much worse 🤦 
I'd fixed the DCO, then went back to fix the PostgreSQL styling, and it all went downhill from there. I can't get the DCO check to work now. I'm happy to start over if you want to delete this PR.

**Comment by brian-brazil** [comment]
You can try squashing it, but failing that a new PR is fine if you want.

**Pull request closed without merging**
