### PR TITLE
Add perf exporter

### PR DESCRIPTION
**Pull request by hodgesds**
Signed-off-by: Daniel Hodges <hodges.daniel.scott@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Hmm, does this cover things that the ebpf exporter doesn't? We try to avoid overlap on this page.

**Comment by hodgesds** [comment]
It uses kprobes directly, eBPF programs (generally) need to be compiled with kernel headers unless another eBPF frontend is used like in [this project](https://github.com/weaveworks/tcptracer-bpf). The main benefit that the `perf_exporter` has is that by using kprobes directly you don't need to compile any eBPF programs. So much in the same way a helicopter and airplane are both methods of flying the means of doing so is rather different.

**Comment by brian-brazil** [comment]
From https://github.com/cloudflare/ebpf_exporter#examples there seems to be overlap, and your exporter is quite new.

**Comment by brian-brazil** [comment]
I haven't heard back, so I'll presume that this is already covered by the ebpf exporter. It also looks like nothing has happened on this project since.

**Pull request closed without merging**
