### PR TITLE
Link to Clojure client

### PR DESCRIPTION
**Pull request by carlduevel**
I'd like to add a Clojure client I wrote a while ago.
All feedback is welcome!

### CODE REVIEW

**Comment by SuperQ** [comment]
Interesting, your README talks about not having to register metrics. This is a bit odd for a typical Prometheus implementation. In Prometheus, we expect things like counters to exist from startup time, and stay existing until the process exits. We try to [avoid metrics that appear and disappear](https://www.robustperception.io/existential-issues-with-metrics).

The classic problem here is having an error counter that starts at 1, because the counter gets created on the first increment. So if you want to alert on `increase(errors_total[5m])`, a single increment won't fire because it didn't start out at zero.

**Comment by brian-brazil** [comment]
Thanks for sharing. To make things easier for users, we try to list only one client per language/runtime and there's already a Java client.

**Comment by SuperQ** [comment]
While I agree that it's good to have one option per language/runtime. Clojure is different enough that it probably deserves a dedicated client.

**Comment by brian-brazil** [comment]
It's still on the JVM, and can use the Java client which has better usage in this case at least. Otherwise we'll have every JVM language looking for a link.

**Comment by hackbert** [comment]
Thanks for your quick feedback @SuperQ and @brian-brazil!

To your point about the avoidance of metrics that appear and disappear
@SuperQ, I will update the documentation of the project to advocate
defining metrics upfront (aka registering them).

About the question of listing clients for different languages:
When I initially wanted to instrument some Clojure and Scala
applications I was surprised to not find any clients in those
languages on the list, because at least in my experience as soon
as a Java library gets popular it immediately gets at least wrapped
by somebody to accommodate the language better than Java does.
And of course that is what people have done in many JVM languages
which is an indicator of the popularity of Prometheus in those
communities. So in a way this client list does not do justice to
that widespread use.

There is an Elixir and Erlang client on the list and I think that
is a good choice you made because people writing Elixir will prefer
a client with an interface in Elixir to one in Erlang though they are running
their code on the same VM.

**Comment by brian-brazil** [comment]
Wrappers are fine (there's a section down the bottom for them), brand new client libraries on a given runtime are not in terms of duplication. If duplicates have slipped in, we'll clean them up at some point.

**Pull request closed without merging**
