### PR TITLE
update histograms.md

### PR DESCRIPTION
**Pull request by viktoryi**
Seems it's a descriptive error.

Signed-off-by: Viktor Yi <viktoryi@163.com>

### CODE REVIEW

**Comment by RichiH** [comment]
Our buckets are `le`; thus "upper, inclusive". The phrasing seems to be correct, to me.

**Comment by SuperQ** [comment]
The wording is correct as-is.

**Comment by viktoryi** [comment]
Here is the document for now, and there are two `upper bound` in this sentence. That's why I'm confused.
> a bucket with the target request duration as the upper bound and another bucket with the tolerated request duration (usually 4 times the target request duration) as the upper bound

**Comment by viktoryi** [comment]
Here is the document for now, and there are two `upper bound` in this sentence. That's why I'm confused.
> a bucket with the target request duration as the upper bound and another bucket with the tolerated request duration (usually 4 times the target request duration) as the upper bound

**Comment by beorn7** [comment]
Oops. In fact, "upper bound" is mentioned twice in an attempt to be _less_ confusing and _more_ explicit. (o:

The "upper bound" is not coming from APDEX but from the Prometheus histogram, where an "upper bound" is what you configure for each bucket. If there's a better way to phrase it, suggestions are welcome.

**Pull request closed without merging**
