### PR TITLE
Add Ballerina to the list of software exposing Prometheus metrics

### PR DESCRIPTION
**Pull request by chrishantha**
[Ballerina](https://ballerina.io/) is a programming language for integration. Ballerina services are by default [observable](https://ballerina.io/learn/how-to-observe-ballerina-code/) and it supports Prometheus. Ballerina run-time will start an HTTP endpoint for Prometheus to scrape metrics when observability is enabled.

This PR adds Ballerina to the list of software exposing Prometheus metrics.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Looks like this is the appropriate category as this is not a Prometheus client library, it's only exposing data in the Prometheus format. It's actually micrometer instrumentation under the covers.

**Comment by chrishantha** [comment]
Thanks @brian-brazil!

Yes, we use Micrometer for now. We are currently working on a Ballerina specific Metrics API implementation. We are also working on a Ballerina service, which will export Ballerina Metrics in Prometheus format. Once we have that, we are going to stop using Micrometer.

**Comment by brian-brazil** [comment]
If you plan on being Prometheus based you should take a look at https://prometheus.io/docs/instrumenting/writing_clientlibs/, and we're here to help if you've any questions around that.

**Comment by chrishantha** [comment]
Thanks for the information. We will look at it.

**Pull request merged**
