### PR TITLE
Add rolling summit doc

### PR DESCRIPTION
**Pull request by RichiH**
Signed-off-by: Richard Hartmann <richih@richih.org>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I need to think about this, it might be better to have it on the list below.

**Comment by RichiH** [comment]
It's objectively better with the PR merged and easy to change...

**Comment by juliusv** [comment]
I think it's fine from my side as a first step :+1:

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
