### PR TITLE
Added CardRates.png to index.html

### PR DESCRIPTION
**Pull request by db-roberto**
Signed-off-by: Roberto Sanchez <roberto@digitalbrands.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. I believe this company was already added in #1111

**Comment by db-roberto** [comment]
This PR is for CardRates.com

**Comment by brian-brazil** [comment]
Both PRs appear to be from the same company, and we try to list each company only once. I'd suggest changing the existing one to Digital Brands to show that the company is using Prometheus rather than just a website.

**Comment by db-roberto** [comment]
Oh, I see what you're saying. Thanks!

**Pull request closed without merging**
