### PR TITLE
Add mysqlrouter_exporter

### PR DESCRIPTION
**Pull request by rluisr**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for sharing. Your exporter it taking a password on the command line, which is not secure. Can you fix that?

Some other tips to improve your exporter:
Several label names should be separate metrics as they are numeric, including process_id, time_started, time_refresh_in_ms, group_replication_id, time_last_refresh_succeeded, refresh_failed. router_status should be router_info.
Metrics should be gathered at scrape time and use MustNewConstMetric, not on a 60s cycle independent of scrapes.

**Comment by rluisr** [comment]
OK I'll change reading credentials from command line to an environment variable.

> Several label names should be separate metrics as they are numeric, including process_id, time_started, time_refresh_in_ms, group_replication_id, time_last_refresh_succeeded, refresh_failed. router_status should be router_info.

It's means change label like below?
```
router_info{process_id=x, time_started=x, time_refresh_in_ms=x, group_replication_id=x, time_last_refresh_succeeded=x, refresh_failed=x}
```

**Comment by brian-brazil** [comment]
> It's means change label like below?

Yes, and remove the numeric labels. Instead have them as separate gauge metrics. You can't do math on label values.

**Comment by rluisr** [comment]
Thanks quick reply!
I know labels can't math. but for example `process_id` there is no problem even if wen can't math currently.

I updated code of getting credentials.
please check again :-)
https://github.com/rluisr/mysqlrouter_exporter

**Comment by brian-brazil** [comment]
R sorts before S

**Comment by rluisr** [comment]
Ah sorry. fixed.

**Comment by brian-brazil** [comment]
y is after S :)

**Comment by rluisr** [comment]
oh my god.... sorry

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
