### PR TITLE
add FinOps-related exporters

### PR DESCRIPTION
**Pull request by gluckzhang**
In order to analyze cloud costs and align them with various business metrics, we would like to have a set of cost exporters. They query costs from different cloud providers and expose them as Prometheus metrics. This PR adds the following FinOps-related exporters:
- AWS Cost Exporter
- Azure Cost Exporter
- Kubernetes Cost Exporter

PS: I am not sure about which category should I put these exporters to. Since these exporters expose cost metrics, I created a new category called `FinOps`. Please feel free to comment or adjust the category directly. Thanks!

<details>
<summary>Sample output of AWS Cost Exporter</summary>

*Sensitive information has been masked.*

```
# HELP aws_daily_cost_usd Daily cost of an AWS account in USD
# TYPE aws_daily_cost_usd gauge
aws_daily_cost_usd{ChargeType="Usage",EnvironmentName="sandbox",ProjectName="myproject",Publisher="<aws_account_1>",RegionName="eu-central-1"} 10.1827240691
aws_daily_cost_usd{ChargeType="Usage",EnvironmentName="sandbox",ProjectName="myproject",Publisher="<aws_account_1>",RegionName="other"} 4.258201088100001
aws_daily_cost_usd{ChargeType="Usage",EnvironmentName="prod",ProjectName="myproject",Publisher="<aws_account_2>",RegionName="eu-central-1"} 68.6121380948
aws_daily_cost_usd{ChargeType="Usage",EnvironmentName="prod",ProjectName="myproject",Publisher="<aws_account_2>",RegionName="other"} 2.6191806712
...
...
```
</details>

<details>
<summary>Sample output of Azure Cost Exporter</summary>

*Sensitive information has been masked.*

```
# HELP azure_daily_cost_usd Daily cost of an Azure account in USD
# TYPE azure_daily_cost_usd gauge
azure_daily_cost_usd{ChargeType="ActualCost",EnvironmentName="prod",ProjectName="myproject",ServiceName="Virtual Network",Subscription="<subscription_id_1>",TenantId="<tenant_id_1>"} 0.439500230497108
azure_daily_cost_usd{ChargeType="ActualCost",EnvironmentName="prod",ProjectName="myproject",ServiceName="VPN Gateway",Subscription="<subscription_id_1>",TenantId="<tenant_id_1>"} 4.191000368311904
azure_daily_cost_usd{ChargeType="ActualCost",EnvironmentName="dev",ProjectName="myproject",ServiceName="Azure Container Apps",Subscription="<subscription_id_2>",TenantId="<tenant_id_2>"} 0.371846875438938
azure_daily_cost_usd{ChargeType="ActualCost",EnvironmentName="dev",ProjectName="myproject",ServiceName="Service Bus",Subscription="<subscription_id_2>",TenantId="<tenant_id_2>"} 13.99512952148999
...
```

</details>

<details>
<summary>Sample output of Kubernetes Cost Exporter</summary>

```
# HELP kubernetes_daily_cost_usd Kubernetes daily cost in USD aggregated by namespace
# TYPE kubernetes_daily_cost_usd gauge
kubernetes_daily_cost_usd{namespace="ingress"} 0.9518491293125411
kubernetes_daily_cost_usd{namespace="ns1"} 1.6744666615442327
kubernetes_daily_cost_usd{namespace="ns2"} 0.7495529489062231
kubernetes_daily_cost_usd{namespace="ns3"} 1.0655696937099663
kubernetes_daily_cost_usd{namespace="kube-system"} 1.1914006049581642
...
```

</details>

### CODE REVIEW

**Comment by juliusv** [comment]
@gluckzhang Nice, thanks! I think the "FinOps" section makes sense. If someone disagrees later, they can always move them to another section :)

Could you share some example metrics outputs of these exporters, just to make sure they are somewhat within Prometheus metrics conventions / guidelines?

**Comment by juliusv** [comment]
@gluckzhang Oh sorry, I missed those collapsible sections, thanks! So the conventions I was referring to were https://prometheus.io/docs/practices/naming/ and https://prometheus.io/docs/instrumenting/writing_exporters. Yeah, two points that jump out to me:

* Usually we'd want to have a unit in the metric name, as otherwise it's not clear what currency this is in. Here I'd expect a currency like `usd` or such to be part of the metric name. If the metric name is not a good place for that for some reason, putting it into a label or even (in special cases) into another time series that can be joined in on compatible labels could be an ok-ish alternative. Not sure though if there are any complications around the currency with these exporters?
* Having the rest of the metric name be more descriptive (as you said) would indeed be a good idea. Think about it from the perspective of someone new to your exporter, maybe even just some casual consumer who was not involved in setting up the exporter: if they just look at the metric name, will they be confused about the exact meaning of the metric, or can they get a good understanding?

So yeah, maybe something like `aws_daily_cost_usd` is better. Although then I'd still have one question: is that daily cost according to a trailing/moving 24h window, or is that 24h window aligned with fixed times, so it goes up over the day and then suddenly jumps to 0 again when the next 24h period starts? Usually a moving-window approach would be more Prometheus-ish, because otherwise you also need to build your queries and dashboards in a way that they are somehow aligned to fixed-start/end 24h time windows.

Anyway, just some input from someone who doesn't have much knowledge about these exporters, would be great to learn more :)

**Comment by juliusv** [comment]
@gluckzhang I see, thanks for the clarification! Yes, I wouldn't block adding this on the moving-window question. It's a bit of an impedance mismatch with how things are usually done in Prometheus, but with exporters there are also often external constraints leading to those kinds of situations. But maybe it also depends on how people usually want to use the data: always based on a calendar day, or on a moving window.

**Comment by gluckzhang** [comment]
Yes, super agree. The feedback is very helpful, thanks! I will update the metric name, description, and documentation to reflect our discussions. Will let you know once it is ready to merge this PR :)

**Comment by gluckzhang** [comment]
Hi @juliusv, FYI, I have improved the exporters based on your comments. Thank you for giving us feedback. We will keep improving the exporters in the future. Cheers!

- https://github.com/opensourceelectrolux/aws-cost-exporter/pull/1
- https://github.com/opensourceelectrolux/azure-cost-exporter/pull/1
- https://github.com/opensourceelectrolux/kubernetes-cost-exporter/pull/1

**Comment by gluckzhang** [comment]
Hi @juliusv, just in case the GitHub notification does not reach you. We have improved the exporters and now the PR is ready to be merged. Thank you :)

**Comment by juliusv** [comment]
Thanks! :+1:

**Pull request merged**
