### PR TITLE
Add network exporter

### PR DESCRIPTION
**Pull request by syepes**
Addition of the Network Exporter

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. I aim to avoid duplication in this list, and this network exporter seems to duplicate both the blackbox and especially smokeping exporters which are already listed. If there's ways in which you feel those could be improved, I'd encourage you to talk to their maintainers.

**Comment by syepes** [comment]
@brian-brazil  Actually is a mix of both blackbox and smokeping but with more metrics (jitter stats) and features but specially the [MTR](https://en.wikipedia.org/wiki/MTR_(software)) module (traceroute)

**Comment by brian-brazil** [comment]
At the end of the day it's filling the same base use cases that already listed exporters do, so I don't think it makes sense to list this here. You are free to announce your exporter on the -users list.

**Comment by syepes** [comment]
@brian-brazil, Ok no problem

**Pull request closed without merging**
