### PR TITLE
add link to aws emr yarn exporter

### PR DESCRIPTION
**Pull request by jeremietharaud**
@brian-brazil 

Hi,
This is my first contribution to the project, please find a link to my exporter: [AWS EMR YARN Exporter](https://github.com/jeremietharaud/emr-yarn-exporter)

### CODE REVIEW

**Comment by brian-brazil** [comment]
Hmm, does this do anything that the Cloudwatch exporter doesn't? We try to avoid duplication in this list.

**Comment by jeremietharaud** [comment]
Hi Brian,
Thank you for your comment.
My exporter is using YARN API directly to get the metrics. it provides more up-to-date metrics compared to Cloudwatch. Indeed, EMR Cloudwatch metrics are [only updated every 5 minutes](https://docs.aws.amazon.com/emr/latest/ManagementGuide/UsingEMR_ViewingMetrics.html#UsingEMR_ViewingMetrics_HowDoI), which is a bit annoying where your spark jobs take less than one minute.
Thank you.

**Comment by brian-brazil** [comment]
In that case, is this anything the JMX exporter can't expose?

**Comment by jeremietharaud** [comment]
Hi,
I don't think so. My exporter is not a Java agent, it queries the YARN master cluster API that exposes metrics (for cluster, node, queues and scheduler), so no need to get JMX beans. Plus it runs outside of the EMR clusters, like the SQS or ECS exporter.

**Comment by brian-brazil** [comment]
The question is more, is this available via JMX? My vague recollection is that it is for YARN.

**Comment by jeremietharaud** [comment]
Probably, but it is likely to be harder to configure (plus EMR clusters are managed by AWS so we don't have access to the whole configuration).
Using the API is much more straightforward in that case.

**Comment by brian-brazil** [comment]
That counts as duplicating an existing exporter then I'm afraid, if we had an exporter for every possible deployment variation that would lead more to confusion than anything.

**Comment by jeremietharaud** [comment]
I don't think it's a duplication of an existing exporter. My exporter is specific to AWS EMR service insofar as there is an auto-discover of EMR clusters, it also adds the tags of the clusters as label values on the metrics as well as cluster id, name and status, which cloudwatch and jmx exporter cannot do.
I think it would be too bad to limit to a "generic" exporter which configuration is much more complex (conf of the jmx, look for the beans, etc.) and less accurate than my exporter.

**Comment by brian-brazil** [comment]
> as there is an auto-discover of EMR clusters, it also adds the tags of the clusters as label values on the metrics as well as cluster id, name and status

That's the responsibility of Prometheus, not an exporter.

**Comment by jeremietharaud** [comment]
> 
> 
> > as there is an auto-discover of EMR clusters, it also adds the tags of the clusters as label values on the metrics as well as cluster id, name and status
> 
> That's the responsibility of Prometheus, not an exporter.

OK thank you. I will review that.

**Pull request closed without merging**
