### PR TITLE
Add company names to team list in governance

### PR DESCRIPTION
**Pull request by juliusv**
As proposed by @roidelapluie in https://groups.google.com/forum/#!topic/prometheus-developers/ysuEj_Tw9Bw

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
Perhaps we should wait for @mxinden 's :+1: in particular because his current company was half-guessed?

**Comment by juliusv** [comment]
@simonpasquier Thanks!

**Comment by RichiH** [comment]
LGTM

**Pull request merged**
