### PR TITLE
Add new MQTT exporter

### PR DESCRIPTION
**Pull request by torilabs**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks for your pull request.

We try not to split the community and we already have listed:

* [MQTT blackbox exporter](https://github.com/inovex/mqtt_blackbox_exporter)
* [MQTT2Prometheus](https://github.com/hikhvar/mqtt2prometheus)

Is there a reasonable reason to get another MQTT-exporter ? If the existing ones don't meed your needs, did you try to contact their communities?

Thanks.

**Comment by torilabs** [comment]
> Thanks for your pull request.
> 
> We try not to split the community and we already have listed:
> 
> * [MQTT blackbox exporter](https://github.com/inovex/mqtt_blackbox_exporter)
> * [MQTT2Prometheus](https://github.com/hikhvar/mqtt2prometheus)
> 
> Is there a reasonable reason to get another MQTT-exporter ? If the existing ones don't meed your needs, did you try to contact their communities?
> 
> Thanks.

Hi @roidelapluie, you're right that there are some other exporters related to MQTT. But as I get through both of them I've found `mqtt_blackbox_exporter` is just for testing purposes and `mqtt2prometheus` is just for single purpose and looks like for hobby use (not production ready). On the other hand `mqtt-prometheus-exporter` is fully configurable, is docker-ready on multiple platforms, is production ready (contains healthchecking, tests, ...). In the near future it will also support multiple formats of message.
I think for everybody it is always better to know about all the options and choose the project that fits.

**Comment by brian-brazil** [comment]
This sounds like a duplicate of mqtt2prometheus, as both subscribe to mqtt and generate metrics from the messages. If you feel there's features missing from it please work with the existing listing, to avoid splitting the community and/or continuously reinventing the wheel.

**Comment by hikhvar** [comment]
As the author of mqtt2prometheus, I can add that mqtt2prometheus started as a hobby project, but my intention is to support production use as well. If you have a look at the closed issues, I will answer those in a timely manner and have already implemented some feature requests from people who want to use the exporter in production. If there are any missing production features I happily accept pull requests and issues.

**Pull request closed without merging**
