### PR TITLE
add  Alertmanager Webhook: WorkWechat Bot

### PR DESCRIPTION
**Pull request by zgfh**
add  Alertmanager Webhook: WorkWechat Bot

### CODE REVIEW

**Comment by brian-brazil** [comment]
The alertmanager natively supports WeChat: https://prometheus.io/docs/alerting/configuration/#wechat_config

Is this something else?

**Comment by zgfh** [comment]
thanks to reply.
this is work wechat(企业微信), not wechat,  it send message to chat group of user create .
(https://work.weixin.qq.com/api/doc#90000/90136/91770)
I think it will help some company to use

**Comment by brian-brazil** [comment]
It sounds like the on-prem version of WeChat, the WeChat notifier has an api_url configuration field so I'd presume it's also covered.

**Comment by zgfh** [comment]
my bad,Not explained clearly
wechat and work wechat  not same product,  and have different api ,different users
wechat like Twitter (Just for explanation),for use talk
work wechat like slack, for developer or company ,support robot

**Comment by brian-brazil** [comment]
This looks like the same API to me: https://work.weixin.qq.com/api/doc#90000/90003/90487

**Comment by zgfh** [comment]
very sorry ,I didn't look at the document carefully
you are right, alertmanager support work wechat (I thought it was WeChat.) with create app.
but there is two thing too.
custom app: https://work.weixin.qq.com/api/doc#90000/90136/91770
rebot: https://work.weixin.qq.com/api/doc#90000/90003/90487

but I don't want explained, it hard to me😂
if someone really need it, he(she) will find this

**Pull request closed without merging**
