### PR TITLE
We already call these write receivers, not adapters.

### PR DESCRIPTION
**Pull request by brian-brazil**
@juliusv Forgot we'd already named these.

### CODE REVIEW

**Comment by juliusv** [comment]
What would we call a process that does full read+write then? Wouldn't it be better to call it all an "adapter", and thus also call the write path an "adapter" (or part of it), to be less confusing?

**Comment by brian-brazil** [comment]
Thus far we've managed to come up with a different name for every type of data path. I'd worry if we call both "adapter" then we can't tell if someone says e.g. "mysql adapter" whether they're reading or writing.

**Comment by juliusv** [comment]
Hm ok - what do we call a process that does both then? Still adapter? Read-write adapter?

**Comment by brian-brazil** [comment]
I'm not sure to be honest, we're kinda running out of names. "receiving adapter" would be the first one that jumps to mind.

**Comment by juliusv** [comment]
"receiving adapter" sounds like it only receives. How about adapter for both, but just call it "Read adapter", "Write adapter", or "Read/write adapter"? Keeps it simple... it's possible that people won't always use the prefix, but if we make the rules too complicated, they won't name it right anyway :)

**Comment by brian-brazil** [comment]
"receiver" is already in use by a few implementations, as the name has been out there for a while, so probably best not to change it.

Could do with "full adapter" or similar. I imagine the main support load will be with things on the read rather than the write side.

**Comment by juliusv** [comment]
> "receiver" is already in use by a few implementations

I was trying to google this, but only found our demo write receiver, which we can rename. Or are there others? At the same time, that made me notice that we already have the term "receiver" in Alertmanager as a different concept, so that can actually cause confusion.

So that's why I think the "adapter" with read/write qualifiers might still be best?

**Comment by RichiH** [comment]
Loaning from networking, what about receiver, transmitter, and bidi (bi-directional)?

**Comment by brian-brazil** [comment]
> Or are there others?

I found two I think (and I know of one other that you won't find publically), and I've had a blog post up for a good while now too.

> At the same time, that made me notice that we already have the term "receiver" in Alertmanager as a different concept, so that can actually cause confusion.

I recently realised that, there's not much overlap so hopefully that'll work out.

> transmitter, and bidi (bi-directional)?

A read adapter is bi-directional.

**Comment by juliusv** [comment]
> I found two I think (and I know of one other that you won't find publically), and I've had a blog post up for a good while now too.

I don't think such few existing cases should block us from choosing the best possible name for the many years to come.

@RichiH receiver/transmitter has the problem that a read-only adapter usually both receives *and* transmits (to the backend). And "transmitter" doesn't sound like something you can query.

I'm yet to be convinced that we have any term better than "read|write|read/write" adapter"... also, this PR currently wants to define a "Remote Write Receiver" to be a bridge/adapter between Prometheus and a final remote system, while in common English, "receiver" could also mean a system which directly supports remote writes (like Cortex). Something that receives remote writes, that is...

**Comment by brian-brazil** [comment]
> while in common English, "receiver" could also mean a system which directly supports remote writes (like Cortex). Something that receives remote writes, that is...

Yeah, that was my original thinking. We now have endpoint for that too.

**Pull request closed without merging**
