### PR TITLE
Remove reference to --web.enable-remote-shutdown

### PR DESCRIPTION
**Pull request by snebel29**

### CODE REVIEW

**Comment by beorn7** [comment]
IIRC this was true for Prometheus 1.x. The sentence you remove here is referring to 1.x only.

**Comment by beorn7** [comment]
If we wanted to remove anything, we should remove the whole reference to 1.x. What does everybody think about that?

**Comment by snebel29** [comment]
Ah right, I wasn't aware of this existing in 1.X and since the sentence start with `As of Prometheus 2.0`... I keep it open for whatever the fix finally is

**Comment by brian-brazil** [comment]
> If we wanted to remove anything, we should remove the whole reference to 1.x. What does everybody think about that?

Hmm, there's stragglers out there running 1.x. It's out almost 2 years now.

**Comment by snebel29** [comment]
Ok, that was my fault reading too fast, it's in fact stated that this only apply to 1.x

**Pull request closed without merging**
