### PR TITLE
Add Amazon Managed Service for Prometheus (AMP)

### PR DESCRIPTION
**Pull request by matanbaruch**
AWS added Manage Prometheus as read and write service.
https://aws.amazon.com/prometheus/

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. As far as I'm aware this is Cortex, and we list software here rather than every company running that software as a service. We don't list Grafana Cloud either for example, which is also Cortex.

**Comment by matanbaruch** [comment]
Agreed.

But it should be mentioned somewhere, as it is an easy way to implement Prometheus on the cloud. 

Maybe a new managed service section?

**Comment by brian-brazil** [comment]
Listing companies who provide Cortex as a service seems more something for Cortex docs than Prometheus docs.

**Comment by matanbaruch** [comment]
Got it.

**Pull request closed without merging**
