### PR TITLE
Oracle DB Exporter

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
NB: I've not tested it yet

**Comment by brian-brazil** [comment]
You should use ConstMetrics for things like up too.

Let us know when you've tested it.

**Comment by brian-brazil** [comment]
Have you tested this by now?

**Comment by sathieu** [comment]
Not yet (and it is not high on my TODO-list). Will try a quick check soon.

**Comment by brian-brazil** [comment]
This appears to have contributors so I'm going to presume it works.

**Pull request merged**
