### PR TITLE
Add xMatters as an Alertmanager Webhook Receiver

### PR DESCRIPTION
**Pull request by ipugh-xm**
This allows users to send alerts into xMatters.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks!

Please note that the URL is not considered secret and is displayed in the web UI. You could use the http_config token to get API keys, instead of using the URL.

**Comment by ipugh-xm** [comment]
Is there a way in http_config to set a parameter, or would we have to go with bearer token or basic auth instead?

**Comment by roidelapluie** [comment]
You would need basic auth ir bearer token. Note that I am pretty sure that the `username` of basic auth is not mandatory.

**Comment by ipugh-xm** [comment]
I'll add some details on API Key security for our users who want that. Is there anything else I need to do?

**Comment by ipugh-xm** [comment]
@roidelapluie I've added a note telling our users the lack of security with the way the API Key is stored and mentioned the option of basic authentication. Is there anything else I need to do for our integration to be in the docs?

**Comment by roidelapluie** [comment]
Thanks! It is unclear how to use basic auth however, maybe you should consider adding an exemple.

**Pull request merged**
