### PR TITLE
Change the maintainer of apache_exporter.

### PR DESCRIPTION
**Pull request by neezgee**
Hi Prometheus developers!

I'm not very effective as Apache exporter maintainer since I don't actually use it and don't have enough time to do it properly. Luckily, Pedro (Lusitaniae@) is ready to take over it. Please consider it and, if have no other plans for this exporter, update the documentation. Thank you!

### CODE REVIEW

**Comment by Lusitaniae** [comment]
Hi Prometheus people,

Hope to be helpful here!

**Comment by brian-brazil** [comment]
Note that as the new repo is marked as forked that github code search won't work on it.

**Comment by neezgee** [comment]
Brian, thanks for the note, I didn't think about it.

I added a link to it from the old repo. Pedro, did you consider to re-create repository and re-upload code?

**Comment by grobie** [comment]
Best would be to transfer ownership of the repository, Github will then
also create a HTTP redirect from the old address.

**Comment by neezgee** [comment]
Pedro, can you rename your repo? github doesn't allow to transfer repository when the repository with the same name exist on your account.

**Comment by Lusitaniae** [comment]
I renamed it, should be good now

**Comment by neezgee** [comment]
Now it says that "Lusitaniae already has a repository in the neezgee/apache_exporter network". Probably you have to delete it completely.

I've merged you last pull request. If you have other not merged changes, I can merge them too.

**Comment by Lusitaniae** [comment]
I didn't add anything else for now.

Can you please try again Neezgee, I removed the repo.

**Comment by Lusitaniae** [comment]
All good now, 

https://github.com/Lusitaniae/apache_exporter

thanks everyone @neezgee @brian-brazil @grobie

**Pull request merged**
