### PR TITLE
Remove aaS entry from software listOD

### PR DESCRIPTION
**Pull request by RichiH**
Signed-off-by: Richard Hartmann <richih@richih.org>

### CODE REVIEW

**Review by roidelapluie — CHANGES_REQUESTED** [review]
I am blocking this to make sure we first notice them about this and explain them why we do this. I think it should also be part of the commit message.

**Comment by roidelapluie** [comment]
What about newrelic?

**Comment by RichiH** [comment]
I disagree that we are required to keep third parties informed about changes in all cases, but will do so. Do you have contact direct information? CC @ComradeAkko in any case.

New Relic is a distinct piece of software. That there is only one offering by a commercial vendor stands to reason. What would your suggestion be?

**Comment by roidelapluie** [comment]
The split could be : software you install vs software you consume.

**Comment by RichiH** [comment]
That change would be out of scope for the current PR, though. My main intention is to make the list correct as it is defined right now.

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
LGTM, and we have now pinged them via github.

**Comment by roidelapluie** [comment]
> That change would be out of scope for the current PR, though. My main intention is to make the list correct as it is defined right now.

From that perspective that pull request is unambihuous and non controversial. Merged.

**Pull request merged**
