### PR TITLE
Update elasticsearch and postgres exporters with new homes

### PR DESCRIPTION
**Pull request by sysadmind**
These projects have been adopted into the prometheus-community org

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks. Can you attach sample output for both exporters as well, please?

**Comment by sysadmind** [comment]
Sample output of postgres_exporter (abridged):
```
# HELP pg_exporter_last_scrape_duration_seconds Duration of the last scrape of metrics from PostgresSQL.
# TYPE pg_exporter_last_scrape_duration_seconds gauge
pg_exporter_last_scrape_duration_seconds 0.025961232
# HELP pg_exporter_last_scrape_error Whether the last scrape of metrics from PostgreSQL resulted in an error (1 for error, 0 for success).
# TYPE pg_exporter_last_scrape_error gauge
pg_exporter_last_scrape_error 0
# HELP pg_exporter_scrapes_total Total number of times PostgresSQL was scraped for metrics.
# TYPE pg_exporter_scrapes_total counter
pg_exporter_scrapes_total 2
# HELP pg_locks_count Number of locks
# TYPE pg_locks_count gauge
pg_locks_count{datname="postgres",mode="accessexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="accesssharelock",server="localhost:5432"} 1
pg_locks_count{datname="postgres",mode="exclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="rowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="rowsharelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="sharelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="sharerowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="shareupdateexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="postgres",mode="sireadlock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="accessexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="accesssharelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="exclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="rowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="rowsharelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="sharelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="sharerowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="shareupdateexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template0",mode="sireadlock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="accessexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="accesssharelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="exclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="rowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="rowsharelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="sharelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="sharerowexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="shareupdateexclusivelock",server="localhost:5432"} 0
pg_locks_count{datname="template1",mode="sireadlock",server="localhost:5432"} 0
# HELP pg_settings_allow_system_table_mods Allows modifications of the structure of system tables.
# TYPE pg_settings_allow_system_table_mods gauge
pg_settings_allow_system_table_mods{server="localhost:5432"} 0
# HELP pg_settings_archive_timeout_seconds Forces a switch to the next WAL file if a new file has not been started within N seconds. [Units converted to seconds.]
# TYPE pg_settings_archive_timeout_seconds gauge
pg_settings_archive_timeout_seconds{server="localhost:5432"} 0
# HELP pg_settings_array_nulls Enable input of NULL elements in arrays.
# TYPE pg_settings_array_nulls gauge
pg_settings_array_nulls{server="localhost:5432"} 1
# HELP pg_settings_authentication_timeout_seconds Sets the maximum allowed time to complete client authentication. [Units converted to seconds.]
# TYPE pg_settings_authentication_timeout_seconds gauge
pg_settings_authentication_timeout_seconds{server="localhost:5432"} 60
# HELP pg_settings_autovacuum Starts the autovacuum subprocess.
# TYPE pg_settings_autovacuum gauge
pg_settings_autovacuum{server="localhost:5432"} 1
# HELP pg_settings_autovacuum_analyze_scale_factor Number of tuple inserts, updates, or deletes prior to analyze as a fraction of reltuples.
# TYPE pg_settings_autovacuum_analyze_scale_factor gauge
pg_settings_autovacuum_analyze_scale_factor{server="localhost:5432"} 0.1
# HELP pg_settings_autovacuum_analyze_threshold Minimum number of tuple inserts, updates, or deletes prior to analyze.
# TYPE pg_settings_autovacuum_analyze_threshold gauge
pg_settings_autovacuum_analyze_threshold{server="localhost:5432"} 50
# HELP pg_settings_autovacuum_freeze_max_age Age at which to autovacuum a table to prevent transaction ID wraparound.
# TYPE pg_settings_autovacuum_freeze_max_age gauge
pg_settings_autovacuum_freeze_max_age{server="localhost:5432"} 2e+08
# HELP pg_settings_autovacuum_max_workers Sets the maximum number of simultaneously running autovacuum worker processes.
# TYPE pg_settings_autovacuum_max_workers gauge
pg_settings_autovacuum_max_workers{server="localhost:5432"} 3
# HELP pg_settings_autovacuum_multixact_freeze_max_age Multixact age at which to autovacuum a table to prevent multixact wraparound.
# TYPE pg_settings_autovacuum_multixact_freeze_max_age gauge
pg_settings_autovacuum_multixact_freeze_max_age{server="localhost:5432"} 4e+08
# HELP pg_settings_autovacuum_naptime_seconds Time to sleep between autovacuum runs. [Units converted to seconds.]
# TYPE pg_settings_autovacuum_naptime_seconds gauge
pg_settings_autovacuum_naptime_seconds{server="localhost:5432"} 60
# HELP pg_settings_autovacuum_vacuum_cost_delay_seconds Vacuum cost delay in milliseconds, for autovacuum. [Units converted to seconds.]
# TYPE pg_settings_autovacuum_vacuum_cost_delay_seconds gauge
pg_settings_autovacuum_vacuum_cost_delay_seconds{server="localhost:5432"} 0.002
# HELP pg_settings_autovacuum_vacuum_cost_limit Vacuum cost amount available before napping, for autovacuum.
# TYPE pg_settings_autovacuum_vacuum_cost_limit gauge
pg_settings_autovacuum_vacuum_cost_limit{server="localhost:5432"} -1
# HELP pg_settings_autovacuum_vacuum_insert_scale_factor Number of tuple inserts prior to vacuum as a fraction of reltuples.
# TYPE pg_settings_autovacuum_vacuum_insert_scale_factor gauge
pg_settings_autovacuum_vacuum_insert_scale_factor{server="localhost:5432"} 0.2
# HELP pg_settings_autovacuum_vacuum_insert_threshold Minimum number of tuple inserts prior to vacuum, or -1 to disable insert vacuums.
# TYPE pg_settings_autovacuum_vacuum_insert_threshold gauge
pg_settings_autovacuum_vacuum_insert_threshold{server="localhost:5432"} 1000
# HELP pg_settings_autovacuum_vacuum_scale_factor Number of tuple updates or deletes prior to vacuum as a fraction of reltuples.
# TYPE pg_settings_autovacuum_vacuum_scale_factor gauge
pg_settings_autovacuum_vacuum_scale_factor{server="localhost:5432"} 0.2
# HELP pg_settings_autovacuum_vacuum_threshold Minimum number of tuple updates or deletes prior to vacuum.
# TYPE pg_settings_autovacuum_vacuum_threshold gauge
pg_settings_autovacuum_vacuum_threshold{server="localhost:5432"} 50
# HELP pg_settings_autovacuum_work_mem_bytes Sets the maximum memory to be used by each autovacuum worker process. [Units converted to bytes.]
# TYPE pg_settings_autovacuum_work_mem_bytes gauge
pg_settings_autovacuum_work_mem_bytes{server="localhost:5432"} -1
# HELP pg_settings_backend_flush_after_bytes Number of pages after which previously performed writes are flushed to disk. [Units converted to bytes.]
# TYPE pg_settings_backend_flush_after_bytes gauge
pg_settings_backend_flush_after_bytes{server="localhost:5432"} 0
# HELP pg_settings_bgwriter_delay_seconds Background writer sleep time between rounds. [Units converted to seconds.]
# TYPE pg_settings_bgwriter_delay_seconds gauge
pg_settings_bgwriter_delay_seconds{server="localhost:5432"} 0.2
# HELP pg_settings_bgwriter_flush_after_bytes Number of pages after which previously performed writes are flushed to disk. [Units converted to bytes.]
# TYPE pg_settings_bgwriter_flush_after_bytes gauge
pg_settings_bgwriter_flush_after_bytes{server="localhost:5432"} 524288
# HELP pg_settings_bgwriter_lru_maxpages Background writer maximum number of LRU pages to flush per round.
# TYPE pg_settings_bgwriter_lru_maxpages gauge
pg_settings_bgwriter_lru_maxpages{server="localhost:5432"} 100
# HELP pg_settings_bgwriter_lru_multiplier Multiple of the average buffer usage to free per round.
# TYPE pg_settings_bgwriter_lru_multiplier gauge
pg_settings_bgwriter_lru_multiplier{server="localhost:5432"} 2
# HELP pg_settings_block_size Shows the size of a disk block.
# TYPE pg_settings_block_size gauge
pg_settings_block_size{server="localhost:5432"} 8192
# HELP pg_settings_bonjour Enables advertising the server via Bonjour.
# TYPE pg_settings_bonjour gauge
pg_settings_bonjour{server="localhost:5432"} 0
# HELP pg_settings_check_function_bodies Check function bodies during CREATE FUNCTION.
# TYPE pg_settings_check_function_bodies gauge
pg_settings_check_function_bodies{server="localhost:5432"} 1
```

Sample output of elasticsearch_exporter (abridged):
```
# HELP elasticsearch_breakers_estimated_size_bytes Estimated size in bytes of breaker
# TYPE elasticsearch_breakers_estimated_size_bytes gauge
elasticsearch_breakers_estimated_size_bytes{breaker="accounting",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_estimated_size_bytes{breaker="fielddata",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_estimated_size_bytes{breaker="in_flight_requests",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_estimated_size_bytes{breaker="model_inference",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_estimated_size_bytes{breaker="parent",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1.3183728e+08
elasticsearch_breakers_estimated_size_bytes{breaker="request",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
# HELP elasticsearch_breakers_limit_size_bytes Limit size in bytes for breaker
# TYPE elasticsearch_breakers_limit_size_bytes gauge
elasticsearch_breakers_limit_size_bytes{breaker="accounting",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 7.88529152e+08
elasticsearch_breakers_limit_size_bytes{breaker="fielddata",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 3.1541166e+08
elasticsearch_breakers_limit_size_bytes{breaker="in_flight_requests",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 7.88529152e+08
elasticsearch_breakers_limit_size_bytes{breaker="model_inference",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 3.94264576e+08
elasticsearch_breakers_limit_size_bytes{breaker="parent",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 7.49102694e+08
elasticsearch_breakers_limit_size_bytes{breaker="request",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 4.73117491e+08
# HELP elasticsearch_breakers_overhead Overhead of circuit breakers
# TYPE elasticsearch_breakers_overhead counter
elasticsearch_breakers_overhead{breaker="accounting",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1
elasticsearch_breakers_overhead{breaker="fielddata",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1.03
elasticsearch_breakers_overhead{breaker="in_flight_requests",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 2
elasticsearch_breakers_overhead{breaker="model_inference",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1
elasticsearch_breakers_overhead{breaker="parent",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1
elasticsearch_breakers_overhead{breaker="request",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 1
# HELP elasticsearch_breakers_tripped tripped for breaker
# TYPE elasticsearch_breakers_tripped counter
elasticsearch_breakers_tripped{breaker="accounting",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_tripped{breaker="fielddata",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_tripped{breaker="in_flight_requests",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_tripped{breaker="model_inference",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_tripped{breaker="parent",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
elasticsearch_breakers_tripped{breaker="request",cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",name="ef3086fca86e"} 0
# HELP elasticsearch_cluster_health_active_primary_shards The number of primary shards in your cluster. This is an aggregate total across all indices.
# TYPE elasticsearch_cluster_health_active_primary_shards gauge
elasticsearch_cluster_health_active_primary_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_active_shards Aggregate total of all shards across all indices, which includes replica shards.
# TYPE elasticsearch_cluster_health_active_shards gauge
elasticsearch_cluster_health_active_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_delayed_unassigned_shards Shards delayed to reduce reallocation overhead
# TYPE elasticsearch_cluster_health_delayed_unassigned_shards gauge
elasticsearch_cluster_health_delayed_unassigned_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_initializing_shards Count of shards that are being freshly created.
# TYPE elasticsearch_cluster_health_initializing_shards gauge
elasticsearch_cluster_health_initializing_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_json_parse_failures Number of errors while parsing JSON.
# TYPE elasticsearch_cluster_health_json_parse_failures counter
elasticsearch_cluster_health_json_parse_failures 0
# HELP elasticsearch_cluster_health_number_of_data_nodes Number of data nodes in the cluster.
# TYPE elasticsearch_cluster_health_number_of_data_nodes gauge
elasticsearch_cluster_health_number_of_data_nodes{cluster="docker-cluster"} 1
# HELP elasticsearch_cluster_health_number_of_in_flight_fetch The number of ongoing shard info requests.
# TYPE elasticsearch_cluster_health_number_of_in_flight_fetch gauge
elasticsearch_cluster_health_number_of_in_flight_fetch{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_number_of_nodes Number of nodes in the cluster.
# TYPE elasticsearch_cluster_health_number_of_nodes gauge
elasticsearch_cluster_health_number_of_nodes{cluster="docker-cluster"} 1
# HELP elasticsearch_cluster_health_number_of_pending_tasks Cluster level changes which have not yet been executed
# TYPE elasticsearch_cluster_health_number_of_pending_tasks gauge
elasticsearch_cluster_health_number_of_pending_tasks{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_relocating_shards The number of shards that are currently moving from one node to another node.
# TYPE elasticsearch_cluster_health_relocating_shards gauge
elasticsearch_cluster_health_relocating_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_status Whether all primary and replica shards are allocated.
# TYPE elasticsearch_cluster_health_status gauge
elasticsearch_cluster_health_status{cluster="docker-cluster",color="green"} 1
elasticsearch_cluster_health_status{cluster="docker-cluster",color="red"} 0
elasticsearch_cluster_health_status{cluster="docker-cluster",color="yellow"} 0
# HELP elasticsearch_cluster_health_task_max_waiting_in_queue_millis Tasks max time waiting in queue.
# TYPE elasticsearch_cluster_health_task_max_waiting_in_queue_millis gauge
elasticsearch_cluster_health_task_max_waiting_in_queue_millis{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_total_scrapes Current total ElasticSearch cluster health scrapes.
# TYPE elasticsearch_cluster_health_total_scrapes counter
elasticsearch_cluster_health_total_scrapes 2
# HELP elasticsearch_cluster_health_unassigned_shards The number of shards that exist in the cluster state, but cannot be found in the cluster itself.
# TYPE elasticsearch_cluster_health_unassigned_shards gauge
elasticsearch_cluster_health_unassigned_shards{cluster="docker-cluster"} 0
# HELP elasticsearch_cluster_health_up Was the last scrape of the ElasticSearch cluster health endpoint successful.
# TYPE elasticsearch_cluster_health_up gauge
elasticsearch_cluster_health_up 1
# HELP elasticsearch_clusterinfo_last_retrieval_success_ts Timestamp of the last successful cluster info retrieval
# TYPE elasticsearch_clusterinfo_last_retrieval_success_ts gauge
elasticsearch_clusterinfo_last_retrieval_success_ts{url="http://localhost:9200"} 1.626291799e+09
# HELP elasticsearch_clusterinfo_up Up metric for the cluster info collector
# TYPE elasticsearch_clusterinfo_up gauge
elasticsearch_clusterinfo_up{url="http://localhost:9200"} 1
# HELP elasticsearch_clusterinfo_version_info Constant metric with ES version information as labels
# TYPE elasticsearch_clusterinfo_version_info gauge
elasticsearch_clusterinfo_version_info{build_date="2021-05-28T17:40:59.346932922Z",build_hash="9a7758028e4ea59bcab41c12004603c5a7dd84a9",cluster="docker-cluster",cluster_uuid="wCgQgbGTTh6P5qv0yM_Obw",lucene_version="8.8.2",version="7.13.1"} 0
# HELP elasticsearch_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which elasticsearch_exporter was built.
# TYPE elasticsearch_exporter_build_info gauge
elasticsearch_exporter_build_info{branch="",goversion="go1.16.6",revision="",version=""} 1
# HELP elasticsearch_filesystem_data_available_bytes Available space on block device in bytes
# TYPE elasticsearch_filesystem_data_available_bytes gauge
elasticsearch_filesystem_data_available_bytes{cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",mount="/ (overlay)",name="ef3086fca86e",path="/usr/share/elasticsearch/data/nodes/0"} 1.14980528128e+11
# HELP elasticsearch_filesystem_data_free_bytes Free space on block device in bytes
# TYPE elasticsearch_filesystem_data_free_bytes gauge
elasticsearch_filesystem_data_free_bytes{cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",mount="/ (overlay)",name="ef3086fca86e",path="/usr/share/elasticsearch/data/nodes/0"} 1.14980528128e+11
# HELP elasticsearch_filesystem_data_size_bytes Size of block device in bytes
# TYPE elasticsearch_filesystem_data_size_bytes gauge
elasticsearch_filesystem_data_size_bytes{cluster="docker-cluster",es_client_node="true",es_data_node="true",es_ingest_node="true",es_master_node="true",host="172.17.0.3",mount="/ (overlay)",name="ef3086fca86e",path="/usr/share/elasticsearch/data/nodes/0"} 4.76630163456e+11

```

**Comment by RichiH** [comment]
Nits, but will merge

* pg_settings_autovacuum_multixact_freeze_max_age should end in seconds
* elasticsearch_cluster_health_total_scrapes should end in scrapes_total
* elasticsearch_breakers_overhead & _tripped should end in _total

**Comment by RichiH** [comment]
Thanks!

**Comment by sysadmind** [comment]
@RichiH I'm working on refactoring both projects to bring them in line with standards. Thanks for the feedback.

**Comment by RichiH** [comment]
@sysadmind do you want to take the nits upstream or would you prefer if I did?

**Comment by sysadmind** [comment]
I can handle it. I have already started fixing the postgres_exporter. Thanks!

**Pull request merged**
