### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by tredondo**

### CODE REVIEW

**Comment by tredondo** [comment]
I see the DCO has failed. This was a drive-by edit from the GitHub interface. I don't know how to sign off here. Please do the needful.

**Review by RichiH — CHANGES_REQUESTED** [review]
Thanks! Could you please

* Sign DCO ; see https://github.com/prometheus/docs/pull/2112/checks?check_run_id=5832947733
* use underscore for italics

before we can merge?

**Comment by tredondo** [comment]
As I had mentioned, I was editing from GitHub's UI. I've already donated quite a bit of my time fixing small errors in the project. Making new contributors run through hoops like figuring out how to deal with the DCO (first time I see this in years of GitHubbing), only turns them off.

To make this easier, the DCO page could point to this [browser extension to automatically sign-off commits](https://github.com/scottrigby/dco-gh-ui), or simply explain that all that's required is to add one line to the extended commit message. Right now the DCO page is cryptic and unhelpful for the random contributor.

**Comment by tredondo** [comment]
Superseded by #2117.

**Comment by juliusv** [comment]
> Making new contributors run through hoops like figuring out how to deal with the DCO (first time I see this in years of GitHubbing), only turns them off.

Sorry about that. Unfortunately it's required for legal reasons by CNCF projects. I'm happy we at least don't require a CLA :)

> To make this easier, the DCO page could have a screenshot for how to do this in GitHub, or even better (because people can forget and it's impossible to amend commits via the GitHub UI), point to this [browser extension to automatically sign-off commits](https://github.com/scottrigby/dco-gh-ui) that can automatically sign off commits made via GitHub.

I guess that would be something to take on for the DCO app people where I presume that page comes from (https://github.com/apps/dco). Interesting, I didn't know about the browser extension (I rarely use the GH UI for authoring commits).

**Pull request closed without merging**
