### PR TITLE
Update documentation for the fixed calculation of chunks to persist

### PR DESCRIPTION
**Pull request by beorn7**
@fabxc Documentation for https://github.com/prometheus/prometheus/pull/1345

### CODE REVIEW

**Comment by fabxc** [comment]
:+1:

**Comment by beorn7** [comment]
Thanks. Before I can merge this, I need your eyes on https://github.com/prometheus/prometheus/pull/1345 though.

**Comment by fabxc** [comment]
Yup.

**Comment by beorn7** [comment]
I'll create a separate PR for the "rushed mode" documentation.

**Pull request merged**
