### PR TITLE
Add 'Simple transmission exporter'

### PR DESCRIPTION
**Pull request by sandrotosi**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. We already list an exporter for Transmission, and try to avoid duplicates to avoid splitting the community and continuously reinventing the wheel. If you feel there's features missing from that, please work with the maintainer to.

**Comment by sandrotosi** [comment]
fine.

**Comment by sandrotosi** [comment]
btw, [what maintainer?](https://github.com/metalmatze/transmission-exporter/commit/e578c0e3ff042648a15f76abf520fd50034d876d)

**Comment by brian-brazil** [comment]
I had missed that, however it still appears to be actively maintained, has a built a small community around it over the past 4 years which I'd prefer not to throw that away. Maybe you could talk to @metalmatze about taking it over.

**Comment by sandrotosi** [comment]
sorry, but i'm not going to learn Go just to take over that exporter.

**Comment by metalmatze** [comment]
For now I'm still maintaing the project. I just don't use it myself very actively anymore, thus searching for others to move it forward. Let me know if you want to help.

**Pull request closed without merging**
