### PR TITLE
Update security docs for 2.0 secure by default flags.

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by grobie** [comment]
This page was moved in the versioned-docs branch. Having an entire section for a single page doens't sound right.

**Comment by brian-brazil** [comment]
Where did you put Integrations? This would be similar general operation stuff.

**Comment by grobie** [comment]
There should be only one place where we document flags. This page should
only mention that admin + lifecycle endpoints are dialed by default and
link to the Prometheus config documenting the flags.

**Comment by brian-brazil** [comment]
One of the main purposes of this page is to act as a comprehensive one-stop security audit checklist for Prometheus. Thus exact flag and configuration field names are mentioned, so that they've nice and easy to then grep in config files.

Think of it as a guide - we provide full examples in guides rather than letting the user figure it out from the reference docs.

**Pull request merged**
