### PR TITLE
Added some file-based discovery integrations

### PR DESCRIPTION
**Pull request by jamtur01**
Also tightened language in preceding paragraph a little.

Unsure of the criteria for inclusion so let me know if these are okay.

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'd generally prefer that the authors of these ask to add them, so that we know that they want to be listed and feedback (if any) can be provided. That way any obstacles to being a generally usable integration can get resolved, and our users are pointed at quality integrations 

For example from a quick look 3 of these do not atomically write the file, 2 of them expose secrets in argv and there appears to be some deployment-specific hardcoding going on too.

**Comment by jamtur01** [comment]
Where are the guidelines published for integrations?

**Comment by brian-brazil** [comment]
https://prometheus.io/docs/instrumenting/exporters/ and https://prometheus.io/docs/instrumenting/writing_clientlibs/ are the ones written

**Comment by jamtur01** [comment]
@brian-brazil If I was to jot down some notes on writing file discovery scripts where would you like that. I had in mind something like:

```markdown
* Make your file discovery configurable, don't hardcode options. But preferably also ensure your file discovery will work automatically with its default configuration, for example, the default configuration options assume the default installation state of the source.
* Don't expose secrets like API keys or passwords in configuration. Instead, rely on secret stores or [the environment](https://12factor.net/config).
* Operations on the files to which you output your targets should be atomic.
```

**Comment by brian-brazil** [comment]
I'm not sure we have a place for that yet. It hasn't really come up much. Most SD integrations would be ad-hoc and organisation specific, so there's no real rules beyond the atomic write.

**Comment by jamtur01** [comment]
Okay. I'll just park these here. My primary concern was principle of least surprise: "I wrote a thing ... sorry, the thing doesn't meet the project's criteria ... there are criteria?" :)

**Comment by brian-brazil** [comment]
We have docs for SD generally (https://github.com/prometheus/prometheus/tree/master/discovery), but those requirements are likely quite a bit harder than what we'll end up using here.

**Pull request closed without merging**
