### PR TITLE
naming.md: Talk about cardinality

### PR DESCRIPTION
**Pull request by RichiH**
Thanks to SuperQ :)

### CODE REVIEW

**Comment by brian-brazil** [comment]
We shouldn't be splitting these docs across here and http://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels and ensuring that we've got one consistent message.

**Comment by RichiH** [comment]
Valid point. Should I move the beef of my PR to the other section and replace what's in `naming.md` with a link?

**Comment by brian-brazil** [comment]
That sounds good

**Comment by grobie** [comment]
@RichiH ping

**Comment by RichiH** [comment]
Moved to https://github.com/prometheus/docs/pull/726

**Pull request closed without merging**
