### PR TITLE
Add bitcoin exporter to the list

### PR DESCRIPTION
**Pull request by mmilata**
Permission given by the maintainer in https://github.com/jvstein/bitcoin-prometheus-exporter/issues/14

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for you PR, we try to avoid duplication on this list and this appears to be for the same software as the bitcond exporter we already list. Is this actually something significantly different?

**Comment by mmilata** [comment]
It's a different software (with different metrics) for same bitcoin daemon.

**Comment by brian-brazil** [comment]
We generally only list one exporter for a given piece of software. I'd suggest working with @LePetitBloc to add whatever features you feel that exporter is missing so we end up with one really good exporter.

**Comment by mmilata** [comment]
That sounds great in theory but I doubt it's going to happen. I'd suggest mentioning on the exporter list that it is first-come-first-served only and that users should perhaps search the web to see if there's another exporter that is more actively maintained or one that is more suitable to their needs.

**Comment by SuperQ** [comment]
@mmilata It's not first-come-first-served. If an exporter is abandoned and or a new one comes along that greatly improves on the old one, we are willing to change the canonical listing.

What we are trying to accomplish is avoiding too many simultaneous active forks. Competition in the ecosystem is fine, but we need justification for why we should change our recommendation.

**Pull request closed without merging**
