### PR TITLE
Update architecture diagram

### PR DESCRIPTION
**Pull request by lucperkins**
The architecture diagram on the [overview](https://prometheus.io/docs/introduction/overview/) page could use a bit of an aesthetic reboot so I've reworked it. I plan on many more diagrams in the coming weeks.

You can view the new diagram [here](https://github.com/lucperkins/docs/blob/51a5e5092662ccc5f6d99c166796d1b2268de2e3/static/architecture.svg).

### CODE REVIEW

**Comment by brian-brazil** [comment]
That looks a lot better.

I'd remove DNS (it's farily limited) in favour of say EC2. Custom should be file_sd.

For clarity I'd make it "push metrics at exit", that confuses many people.

I'm not sure we should have the federation from other Prometheus servers there, that's a bit more advanced.

**Comment by SuperQ** [comment]
A separate diagram for "Scaling prometheus" that talks about federation and remote read/write would be useful to replace the federation reference on this diagram.

**Comment by brian-brazil** [comment]
Remote read/write is even more advanced ;)

**Comment by lucperkins** [comment]
@RichiH @SuperQ Agreed on a separate diagram for federated Prometheus. This one is already a bit busy 👍

@RichiH Those outline colors are not well defined, no. The Grafana yellow is based on the color in the logo (and to distinguish it from the Prometheus orange). Happy to change that up. And no, definitely no theme across CNCF as far as I know. I believe that those kinds of aesthetic things tend to be project specific, though an internal discussion surrounding that might be beneficial. Also, pretty is above my pay grade 😄

**Comment by brian-brazil** [comment]
That looks fine, you can grab the EC2 logo from https://aws.amazon.com/architecture/icons/ I think.

**Comment by lucperkins** [comment]
@brian-brazil Are other cloud platforms supported?

**Comment by SuperQ** [comment]
@lucperkins There are over a dozen service discovery methods, it would be a bit much to list all of them.

**Comment by lucperkins** [comment]
@SuperQ I assumed so. That's why I opted for "EC2, etc." rather than including a logo.

**Comment by SuperQ** [comment]
How about "Cloud Providers"?

**Comment by brian-brazil** [comment]
We're listing k8 without listing Marathon or Triton, so I think just listing EC2 is fine.

**Comment by SuperQ** [comment]
K8s is in the CNCF family. :smile:

**Comment by lucperkins** [comment]
Updated with EC2 logo. I don't really like "Pull Sources" as a term. Any suggestions on something better?

**Comment by brian-brazil** [comment]
"targets" is the term we use

I'd also "find metrics scraping targets" -> "discover targets"

SDD -> SSD

**Comment by SuperQ** [comment]
How about "Prometheus Targets" or "Prometheus / OpenMetrics Targets".

**Comment by SuperQ** [comment]
In the bottom right, should we mention "PromQL"?

**Comment by brian-brazil** [comment]
They're all just "Targets"

**Comment by RichiH** [comment]
This is bikesheddy, but Kubernetes & Grafana are actually in our family and endorsed, respectively. Presenting any other things might give the wrong impression in several regards, especially if they are paid.

**Comment by lucperkins** [comment]
@RichiH I've limited SD targets to k8s and `file_sd`.

@brian-brazil I've s/SDD/SSD (derp) and renamed to "targets."

@SuperQ I've made PromQL a little more prominent in the mix.

Any final objections before merging? We can always revisit this. Next up will be a diagram for federated Prometheus.

**Comment by brian-brazil** [comment]
:+1:

**Comment by RichiH** [comment]
We still show pagerduty, but it's better than what we have and we can always do another iteration if need be.

**Comment by RichiH** [comment]
Thanks!

**Comment by juliusv** [comment]
@lucperkins Could you share the source for that picture? The old one we created with draw.io and the XML source is at https://github.com/prometheus/prometheus/tree/master/documentation/images (because the image is also used in the Prometheus README.md).

**Comment by lucperkins** [comment]
@juliusv Hmmm. I was under the impression that LucidChart offered export to a format like JSON, XML, etc. but it's looking like the only offer PDF, PNG, JPG, SVG, and VDX (Visio). How would you prefer to proceed?

**Comment by juliusv** [comment]
@lucperkins Ah ok, that's why I think draw.io is nice - you get to download the full XML source which you can import back later and all info is preserved, and it doesn't need an account.

But assuming someone else signed up for LucidChart, can any of the formats you mention be imported back cleanly without losing info? Maybe Visio?

**Comment by lucperkins** [comment]
@juliusv Yes, Visio would fulfill that requirement. But I've been playing around with draw.io recently and it's very easy and surprisingly powerful. So I'll just redo the image, which shouldn't take much time.

**Comment by juliusv** [comment]
@lucperkins That'd be awesome, thanks. Yeah, draw.io is pretty cool and no fuss!

I actually just signed up to Lucidchart to try it out and I would need a Team or Pro account just to even export to Visio.

**Pull request merged**
