### PR TITLE
Add xamira networks to training and support page

### PR DESCRIPTION
**Pull request by fthorns**
Signed-off-by: Fabian Thorns <fabian@thorns.it>

### CODE REVIEW

**Comment by fthorns** [comment]
@RichiH Sorry for bugging you about one of the less important PRs, I saw this one pending for a while and was wondering if there is anything I forgot or if there is anything I could do to help getting this one merged. Thank you :)

**Comment by roidelapluie** [comment]
Thank you for this. I think the current rule is that the "courses" are limited to online trainings.

**Comment by fthorns** [comment]
Hi @roidelapluie , thanks for the explanation and sorry for the late response. We do actually delivery training online, although it is instructor lead. I assume you're referring to self-paces training only, right? In that case, I could adjust the pull request to only add us to the commercial support section; although I think that the ability to collect instructor led training might be helpful, too. But that is probably another topic. Let me know how you'd like to proceed, if we have a chance to make it at least to the commercial support section I'll make the necessary changes. Thanks! :)

**Comment by juliusv** [comment]
Yeah, Courses is just for self-paced online courses so far, but in general I support the idea of making this page more useful. Frequently people also ask me who could help them with some consulting aspect (since I'm doing less consulting with PromLabs now). If we knew what kinds of services each company offered (hosted service, consulting, self-paced training, live training, software engineering, commercial additional software, ...), then we could add tags and/or make things searchable / filterable somehow. Of course that would require reaching out to the various companies to get better information on what they offer, because it's often not 100% clear to us as well.

**Comment by juliusv** [comment]
Yep, that's a larger project...

Thanks for the adjustment! :+1:

**Pull request merged**
