### PR TITLE
Cleanup old releases

### PR DESCRIPTION
**Pull request by SuperQ**
Cleanup docs for Prometheus 2.0 -> 2.2.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
What is the gain from removing those outdated versions? Do we have an established policy of removing outdated versions (eg keep documentation for the x last releases)?

**Comment by brian-brazil** [comment]
We don't have any such policy yet, this is all still (relatively) new for us.

**Comment by RichiH** [comment]
Unless we are running into actual issues, I would like us to keep docs around longer rather than shorter.

**Comment by SuperQ** [comment]
I was just looking to clean up clutter. I went for this list because 2.0-2.2 are known to be very buggy and we don't support them.

**Comment by beorn7** [comment]
I'd also like to keep old documentation for reference.

**Pull request closed without merging**
