### PR TITLE
provide link to our dashboards to make initial prometheus use easier.

### PR DESCRIPTION
**Pull request by burton-scalefastr**
Adding a reference to our dashboard changes so we can share with the community.

### CODE REVIEW

**Comment by brian-brazil** [comment]
We don't currently curate a list dashboards, I'd suggest uploading them to grafana.net.

**Comment by burton-scalefastr** [comment]
Right.  This is why we wanted to provide a set of curated dashboards - so that new Prometheus users could get up and running.

We plan on maintaining these moving forward so new people can just start using them.

**Comment by brian-brazil** [comment]
You're free to provide them, but I'm not sure it's appropriate to link from Prometheus.io to dashboards that presume one particular non-standard label hierarchy. PMMM isn't something we link either for example.

**Comment by burton-scalefastr** [comment]
What's PMMM?

I agree about the labels. It's one of the issues we wanted to solve.  There is some community effort around container labeling which I think could help on standardization.

I'd like to get the link from prometheus.io so that it's easier for new members in the community to discovery this so that they don't have to repeat the work we did.

If you think it's more appropriate maybe it might be better to have a 'community contribution' section. 

I'm open to both scenarios. I just don't want the work we're doing to languish as we want to establish a community around it.

One of the problems with Grafana is that the dashboards are orphaned... We want to help solve that.

**Comment by brian-brazil** [comment]
If you want to curate dashboards that work for you you're free to do so, however it's way too early to link anything like this from prometheus.io as recommended dashboards and certainly not on this page.

What you could do is one of our user interviews on the blog, which could include a link to these.

**Comment by burton-scalefastr** [comment]
Thanks. Who should I talk to about a user interview.

I guess we're ok with either way - I just don't really want these to languish.

**Comment by brian-brazil** [comment]
I handle those as it happens, I've just sent you an email to start that process.

**Pull request closed without merging**
