### PR TITLE
Add initial glossary

### LINKED ISSUE #177: Add a glossary
We've lots of terms, and I expect some of them (like bridge vs. collector vs exporter) are only in a few people's heads. We should have a glossary.

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #177

### CODE REVIEW

**Comment by RichiH** [comment]
A few comments:

* Nitpicky, but an Exporter is not always a binary.
* A target is always scraped via an exporter (as far as I know)
* Mentioning that PromQL is turing-complete would give most people a better idea of the power it has
* Cross-links between the various definitions in the glossary might be worthwhile. I can do that if you don't want to
* Personal preference, but I would tend towards using absolute, not relative, links in your cross-references as that allows moving around of glossary.md while all links need to be changed if targets move, either way.

**Comment by brian-brazil** [comment]
> Nitpicky, but an exporter is not always a binary.

An exporter is always a binary.

> A target is always scraped via an exporter

Targets are what Prometheus scrapes.

> Mentioning that PromQL is turing-complete would give most people a better idea of the power it has

I'd rather not scare them off :)

> Cross-links between the various definitions in the glossary might be worthwhile. I can do that if you don't want to

That'd be appreciated.

> Personal preference, but I would tend towards using absolute, not relative, links in your cross-references as that allows moving around of glossary.md while all links need to be changed if targets move, either way.

We've currently a mix, and as we were talking about having next-release hosted somewhere then relative make more sense.

**Comment by RichiH** [comment]
> An exporter is always a binary.

snmp_exporter is a script. Again, this is rather nitpicky.

> > Cross-links between the various definitions in the glossary might be worthwhile. I can do that if you don't want to
> That'd be appreciated.

Will do after you merge that in.

> We've currently a mix, and as we were talking about having next-release hosted somewhere then relative make more sense.

Sorry, I meant `[bar](../../foo/bar)` vs `[bar](/quux/foo/bar)`

**Comment by beorn7** [comment]
:+1: 

Eventually, we should clarify terms like _metric_ ws. _metric family_ vs. _time series_ etc.

**Comment by brian-brazil** [comment]
This is just a first pass with the more common confusions, we can add to it over time.

**Comment by RichiH** [comment]
@beorn7 That addition should take you less than 15 minutes :)

**Comment by beorn7** [comment]
@RichiH It's a bit more complicated than you might think…

**Comment by RichiH** [comment]
@beorn7 For the three above, that seems unlikely. I might be missing context, though.

**Comment by juliusv** [comment]
@RichiH I guess the challenge would be that this terminlogy is not used 100% consistently between the client libraries, wire formats, and Prometheus itself.

**Comment by RichiH** [comment]
@juliusv While that increases the workload, that makes normalizing on common nomenclature even more desireable :)

**Comment by juliusv** [comment]
Agreed :)

**Pull request merged**
