### PR TITLE
Add Caddy

### PR DESCRIPTION
**Pull request by roidelapluie**
Caddy has native prom metrics now.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
PR: https://github.com/caddyserver/caddy/pull/3709
It is already released.

**Comment by brian-brazil** [comment]
:+1: 

Given the cardinality issues that have been seen with other proxy systems, it'd be wise to allow the user to configure which caddy_admin_http_requests_total labels they want.

**Comment by roidelapluie** [comment]
> Given the cardinality issues that have been seen with other proxy systems, it'd be wise to allow the user to configure which caddy_admin_http_requests_total labels they want.

cc @hairyhenderson

**Comment by hairyhenderson** [comment]
Thanks for adding this, @roidelapluie!

@brian-brazil the `caddy_admin_http_requests_total` metric in particular is internal and the `path` label (I expect that's what you're referring to) has limited cardinality (i.e. it's not just using `req.URL.Path`).

But, I do agree in general, and I'm planning on adding some more configurability. The initial goal was to just get some basic instrumentation enabled.

**Comment by brian-brazil** [comment]
Ah indeed, it was the non-admin one I meant. Assembling metric names form different places makes it hard to figure out what they are from simple reading/grepping of the code.

**Pull request merged**
