### PR TITLE
Just one char typo

### PR DESCRIPTION
**Pull request by LuboVarga**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks, can you add the DCO?

**Comment by LuboVarga** [comment]
I have no problem with DCO, or any contribution licence. How can I technically add dco to my request? I am a bit lost and links in "the sing-off is missing" part of UI is not helpful.

**Comment by brian-brazil** [comment]
The commit message needs a Signed-off-by line such as the one in https://github.com/prometheus/docs/commit/66a460bfcbead9b410e128214c8029255301d8c8

**Comment by brian-brazil** [comment]
All the commits need that line, so probably easiest to squash them.

**Comment by LuboVarga** [comment]
Ehm, I do not have (easy) access to github from work. I will do it later from home. If squash is possible from web UI (I have not found way), please let me know and I will do it.

**Comment by LuboVarga** [comment]
I hope, done.
Just for future reference of my own:
`git rebase -i HEAD~2`
and use "r" to reword both commits Than forcepush.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
