### PR TITLE
edit passive sentence

### PR DESCRIPTION
**Pull request by cuchalin**
Change the sentence: 'New members may be proposed by any existing member by email to Prometheus-team.
Into: 'Any existing member may propose new members by email to Prometheus-team'
The new sentence is in an active voice. It makes the sentence easier to read for most people.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. The existing wording seems consistent with the style of the rest of the text.

**Comment by beorn7** [comment]
Yeah, agree with @brian-brazil . Passive voice is used a lot here anyway.
In different news, a change to the governance requires a qualified vote. So if we ever did an "improve the language" change, it should probably batch up a bunch of things.

**Comment by brian-brazil** [comment]
This would qualify as an editorial change, so I don't think we'd need a full vote here.

**Comment by beorn7** [comment]
Yes, you are right about the editorial change.

Still, since both of us seem to be happy with the general usage of passive voice in the governance document, and nobody else chimed in, I'm closing this.

**Pull request closed without merging**
