### PR TITLE
Add note on hiring technical writers

### PR DESCRIPTION
**Pull request by fabxc**
We can add the PromCon one back once we found someone. But this seems rather important now.

@alexsomesan @brancz

### CODE REVIEW

**Comment by brancz** [comment]
Can't think of something better, then "get paid for it" (which sounds like an m-turks style micro payment) because I'm unsure whether "We're hiring" is ok from legal perspective. But if there are no objections I'm fine with this 👍 . Maybe we can ask the CNCF what wording they would prefer.

**Comment by RichiH** [comment]
"We are looking for freelance workers interested working on this"?

Adding a rough indication of compensation levels might help, or not.


Richard

**Comment by fabxc** [comment]
Updated

**Comment by brancz** [comment]
lgtm 👍

**Comment by alexsomesan** [comment]
👍 nice. fingers crossed now.

**Comment by RichiH** [comment]
+1

**Pull request merged**
