### PR TITLE
Installing Prometheus by Sparrowdo

### PR DESCRIPTION
**Pull request by melezhik**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for the PR. I've never heard of this configuration management system, and I want to keep this list to things that lots of people use. How many people are using this?

**Comment by melezhik** [comment]
Hi @brian-brazil ! Not that many. However it's easy and fast way to install prometheus. Actually Sparrowdo is known for people writting Perl6 code, as it written on Perl6.

**Comment by brian-brazil** [comment]
The goal of this list is to help users with infrastructure they already have, not to have the project suggest new infrastructure.

**Comment by melezhik** [comment]
Hi @brian-brazil , not sure what you mean ...

**Comment by jamtur01** [comment]
@melezhik The installation page details methods for commonly used tools. I believe @brian-brazil is saying that your tool does not have widespread enough usage to include.

**Comment by melezhik** [comment]
Well, fill free to close this one.

however:
> The goal of this list is to help users with infrastructure _they already have_

There are already people who use Sparrowdo, so I can't see the point of "new infrastructure."

**Pull request closed without merging**
