### PR TITLE
Document remote write config.

### LINKED ISSUE #582: Document remote write relabeling

### LINKED ISSUE #583: Document remote write configuration

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #582
Fixes #583

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Since this configuration is only useful in combination with something Prometheus-external, there should be another document at some point (or even embed it here if it's short?) that explains the remote write payload format and how to make use of it. Maybe just don't close issue https://github.com/prometheus/docs/issues/583 completely yet?

**Comment by brian-brazil** [comment]
As it stands I think the demo receiver covers it mostly. It's an experimental feature, I think digging through the code for the few users who want it is okay for now.

**Comment by juliusv** [comment]
Hmm, maybe link to the demo app then at least?

**Comment by juliusv** [comment]
:+1: Thanks

**Pull request merged**
