### PR TITLE
Add bungeecord prometheus exporter

### PR DESCRIPTION
**Pull request by weihao**
Example output
```
# HELP bungeecord_online_players the number of online players in BungeeCord
# TYPE bungeecord_online_players gauge
bungeecord_online_players{server="smp",} 0.0
# HELP bungeecord_player_disconnects_total the number of player disconnects in Velocity
# TYPE bungeecord_player_disconnects_total counter
bungeecord_player_disconnects_total 0.0
# HELP bungeecord_server_list_pings_total the number of server list pings in Velocity
# TYPE bungeecord_server_list_pings_total counter
bungeecord_server_list_pings_total 0.0
# HELP bungeecord_player_connects_total the number of player logins in Velocity
# TYPE bungeecord_player_connects_total counter
bungeecord_player_connects_total 0.0
# HELP bungeecord_jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE bungeecord_jvm_gc_collection_seconds summary
bungeecord_jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 8.0
bungeecord_jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 0.122
bungeecord_jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
bungeecord_jvm_gc_collection_seconds_sum{gc="G1 Old Generation",} 0.0
# HELP bungeecord_jvm_memory JVM memory usage
# TYPE bungeecord_jvm_memory gauge
bungeecord_jvm_memory{type="max",} 2.68435456E8
bungeecord_jvm_memory{type="used",} 4.6992464E7
bungeecord_jvm_memory{type="free",} 2.21442992E8
bungeecord_jvm_memory{type="allocated",} 2.68435456E8
# HELP bungeecord_managed_servers the number of managed servers in Velocity
# TYPE bungeecord_managed_servers gauge
bungeecord_managed_servers 1.0
# HELP bungeecord_jvm_threads_current Current thread count of a JVM
# TYPE bungeecord_jvm_threads_current gauge
bungeecord_jvm_threads_current 35.0
# HELP bungeecord_jvm_threads_daemon Daemon thread count of a JVM
# TYPE bungeecord_jvm_threads_daemon gauge
bungeecord_jvm_threads_daemon 22.0
# HELP bungeecord_jvm_threads_peak Peak thread count of a JVM
# TYPE bungeecord_jvm_threads_peak gauge
bungeecord_jvm_threads_peak 37.0
# HELP bungeecord_jvm_threads_started_total Started thread count of a JVM
# TYPE bungeecord_jvm_threads_started_total counter
bungeecord_jvm_threads_started_total 40.0
# HELP bungeecord_jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE bungeecord_jvm_threads_deadlocked gauge
bungeecord_jvm_threads_deadlocked 0.0
# HELP bungeecord_jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE bungeecord_jvm_threads_deadlocked_monitor gauge
bungeecord_jvm_threads_deadlocked_monitor 0.0
# HELP bungeecord_jvm_threads_state Current count of threads by state
# TYPE bungeecord_jvm_threads_state gauge
bungeecord_jvm_threads_state{state="RUNNABLE",} 9.0
bungeecord_jvm_threads_state{state="TIMED_WAITING",} 19.0
bungeecord_jvm_threads_state{state="BLOCKED",} 0.0
bungeecord_jvm_threads_state{state="WAITING",} 7.0
bungeecord_jvm_threads_state{state="TERMINATED",} 0.0
bungeecord_jvm_threads_state{state="NEW",} 0.0
# HELP bungeecord_player_connects_created the number of player logins in Velocity
# TYPE bungeecord_player_connects_created gauge
bungeecord_player_connects_created 1.637479024887E9
# HELP bungeecord_player_disconnects_created the number of player disconnects in Velocity
# TYPE bungeecord_player_disconnects_created gauge
bungeecord_player_disconnects_created 1.637479024896E9
# HELP bungeecord_server_list_pings_created the number of server list pings in Velocity
# TYPE bungeecord_server_list_pings_created gauge
bungeecord_server_list_pings_created 1.6374790249E9
```

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks for this! Could you add sample output from your exporter, please?

**Comment by weihao** [comment]
@RichiH edited the MR to include example output

**Comment by RichiH** [comment]
Thanks. A few comments re naming:

* bungee_login_total etc -> loginS?
* bungee_players_online_total, bungee_redis_bungee_proxies_online_total, bungee_servers_online_total etc are gauges, so should not end in `total`
* bungee_jvm_gc_collection_seconds_sum bungee_jvm_threads_state etc have trailing commas in their labels
* bungee_ping_total -> pingS?
* bungee_client_connect_total -> connectS (or connections)?
*

**Comment by weihao** [comment]
> Thanks. A few comments re naming:
> 
> * bungee_login_total etc -> loginS?
> * bungee_players_online_total, bungee_redis_bungee_proxies_online_total, bungee_servers_online_total etc are gauges, so should not end in `total`
> * bungee_jvm_gc_collection_seconds_sum bungee_jvm_threads_state etc have trailing commas in their labels
> * bungee_ping_total -> pingS?
> * bungee_client_connect_total -> connectS (or connections)?

Hey @RichiH, thank you for the feedback and I have updated the example output.

- All the names are updated according to the naming conventions.
- For the trailing comma, please see the reference below.

---
The trailing comma is intentional in the Prometheus text format. Quote from https://prometheus.io/docs/prometheus/latest/querying/operators/:
> label list is a list of unquoted labels that may include a trailing comma, i.e. both `(label1, label2)` and `(label1, label2,)` are valid syntax.

The new [OpenMetrics](https://openmetrics.io/) format does not have a trailing comma, so if you get your metrics with the following `Accept:` header you won't see that comma:
```
curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:9999/metrics
```

_Originally posted by @fstab in https://github.com/prometheus/client_java/issues/675#issuecomment-888949597_

**Comment by weihao** [comment]
Hey @RichiH, a friendly ping and let me know what you think.

**Comment by RichiH** [comment]
Thanks for the update and thanks for the poke; can you share another copy of the output, please.

**Comment by weihao** [comment]
@RichiH 
```
# HELP bungee_logins_total logins
# TYPE bungee_logins_total counter
bungee_logins_total 0.0
# HELP bungee_player_connects_total client connect
# TYPE bungee_player_connects_total counter
bungee_player_connects_total 105.0
# HELP bungee_pings_total total pings
# TYPE bungee_pings_total counter
bungee_pings_total 105.0
# HELP bungee_online_servers online servers
# TYPE bungee_online_servers gauge
bungee_online_servers 2.0
# HELP bungee_redis_online_players online redisbungee players
# TYPE bungee_redis_online_players gauge
# HELP bungee_pre_logins_total total pre logins
# TYPE bungee_pre_logins_total counter
bungee_pre_logins_total 0.0
# HELP bungee_redis_bungee_online_proxies total redisbungee online proxy
# TYPE bungee_redis_bungee_online_proxies gauge
bungee_redis_bungee_online_proxies 0.0
# HELP bungee_jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE bungee_jvm_gc_collection_seconds summary
bungee_jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 6.0
bungee_jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 0.285
bungee_jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
bungee_jvm_gc_collection_seconds_sum{gc="G1 Old Generation",} 0.0
# HELP bungee_post_logins_total total post logins
# TYPE bungee_post_logins_total counter
bungee_post_logins_total 0.0
# HELP bungee_jvm_threads_current Current thread count of a JVM
# TYPE bungee_jvm_threads_current gauge
bungee_jvm_threads_current 106.0
# HELP bungee_jvm_threads_daemon Daemon thread count of a JVM
# TYPE bungee_jvm_threads_daemon gauge
bungee_jvm_threads_daemon 16.0
# HELP bungee_jvm_threads_peak Peak thread count of a JVM
# TYPE bungee_jvm_threads_peak gauge
bungee_jvm_threads_peak 107.0
# HELP bungee_jvm_threads_started_total Started thread count of a JVM
# TYPE bungee_jvm_threads_started_total counter
bungee_jvm_threads_started_total 190.0
# HELP bungee_jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE bungee_jvm_threads_deadlocked gauge
bungee_jvm_threads_deadlocked 0.0
# HELP bungee_jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE bungee_jvm_threads_deadlocked_monitor gauge
bungee_jvm_threads_deadlocked_monitor 0.0
# HELP bungee_jvm_threads_state Current count of threads by state
# TYPE bungee_jvm_threads_state gauge
bungee_jvm_threads_state{state="RUNNABLE",} 54.0
bungee_jvm_threads_state{state="WAITING",} 23.0
bungee_jvm_threads_state{state="TERMINATED",} 0.0
bungee_jvm_threads_state{state="TIMED_WAITING",} 29.0
bungee_jvm_threads_state{state="NEW",} 0.0
bungee_jvm_threads_state{state="BLOCKED",} 0.0
# HELP bungee_redis_disconnected_players_total total redis bungee player disconnects
# TYPE bungee_redis_disconnected_players_total counter
bungee_redis_disconnected_players_total 0.0
# HELP bungee_redis_joined_players_total total redis bungee player joins
# TYPE bungee_redis_joined_players_total counter
bungee_redis_joined_players_total 0.0
# HELP bungee_jvm_memory JVM memory usage
# TYPE bungee_jvm_memory gauge
bungee_jvm_memory{type="max",} 4.294967296E9
bungee_jvm_memory{type="used",} 3.36950736E8
bungee_jvm_memory{type="free",} 3.95801656E9
bungee_jvm_memory{type="allocated",} 4.294967296E9
# HELP bungee_player_disconnects_total total player disconnects
# TYPE bungee_player_disconnects_total counter
bungee_player_disconnects_total 0.0
# HELP bungee_online_players unique online players
# TYPE bungee_online_players gauge
bungee_online_players{server="lobby",} 0.0
bungee_online_players{server="smp",} 0.0
# HELP bungee_logins_created logins
# TYPE bungee_logins_created gauge
bungee_logins_created 1.627606405446E9
# HELP bungee_pings_created total pings
# TYPE bungee_pings_created gauge
bungee_pings_created 1.627606405449E9
# HELP bungee_player_connects_created client connect
# TYPE bungee_player_connects_created gauge
bungee_player_connects_created 1.627606405442E9
# HELP bungee_player_disconnects_created total player disconnects
# TYPE bungee_player_disconnects_created gauge
bungee_player_disconnects_created 1.627606405447E9
# HELP bungee_post_logins_created total post logins
# TYPE bungee_post_logins_created gauge
bungee_post_logins_created 1.627606405448E9
# HELP bungee_pre_logins_created total pre logins
# TYPE bungee_pre_logins_created gauge
bungee_pre_logins_created 1.627606405449E9
# HELP bungee_redis_disconnected_players_created total redis bungee player disconnects
# TYPE bungee_redis_disconnected_players_created gauge
bungee_redis_disconnected_players_created 1.627606405483E9
# HELP bungee_redis_joined_players_created total redis bungee player joins
# TYPE bungee_redis_joined_players_created gauge
bungee_redis_joined_players_created 1.627606405478E9
```

**Comment by weihao** [comment]
@RichiH friendly ping

**Comment by weihao** [comment]
@RichiH following up on the PR

**Comment by weihao** [comment]
@RichiH ping

**Comment by RichiH** [comment]
Thanks @weihao , and sorry for the long delay

**Pull request merged**
