### PR TITLE
Add Jamie Wilkinson's  Monitorama workshop to media

### PR DESCRIPTION
**Pull request by grobie**

### CODE REVIEW

**Comment by fabxc** [comment]
:+1: 

We could link to the slides as well – sometimes you cannot watch videos at work or just want a fast overview.

**Comment by juliusv** [comment]
Yes, please also add the slides from https://docs.google.com/presentation/d/1X1rKozAUuF2MVc1YXElFWq9wkcWv3Axdldl8LOH9Vik/edit

**Comment by grobie** [comment]
Do you want to list the talk twice, once under each section, or just add the link to the slides at in the description of the recorded talks?

**Comment by beorn7** [comment]
I'd link the slides next to the video link.

**Comment by fabxc** [comment]
I'd just add a slide link to the video.

**Comment by grobie** [comment]
Done.

**Comment by fabxc** [comment]
Thanks :+1:

**Pull request merged**
