### PR TITLE
Add Awesome Prometheus

### PR DESCRIPTION
**Pull request by beorn7**
Supersedes #1451, picking up the review comments from there.

Signed-off-by: beorn7 <beorn@grafana.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
"High Availability" does not seem to do what it looks like. We put a lot of effort reviewing this list, I don't know if we should point to a 3rd party resource like that.

**Comment by brian-brazil** [comment]
:+1: 

> "High Availability" does not seem to do what it looks like. We put a lot of effort reviewing this list, I don't know if we should point to a 3rd party resource like that.

This is an ancient list, not much curation was involved.

**Comment by beorn7** [comment]
No list will ever be perfect. I don't think a disputed terminology usage should keep us from linking it.

I like the general approach of the "Awesome …" lists. The one linked in this PR is the only Prometheus list in the [central meta list](https://github.com/sindresorhus/awesome). My optimistic approach is that by linking it here, it will only get better.

@roidelapluie is your comment just a general doubt, or is it intended to block merging this PR?

**Comment by roidelapluie** [comment]
> No list will ever be perfect. I don't think a disputed terminology usage should keep us from linking it.
> 
> I like the general approach of the "Awesome …" lists. The one linked in this PR is the only Prometheus list in the [central meta list](https://github.com/sindresorhus/awesome). My optimistic approach is that by linking it here, it will only get better.
> 
> @roidelapluie is your comment just a general doubt, or is it intended to block merging this PR?

general doubt as I know that we generally avoid linking exporter with secrets on command line etc, linking such a list here could expose those unsecure exporters to the community.

but I am fine merging it for the good of the community :)

**Pull request merged**
