### PR TITLE
Add cloudwise to training and support page

### PR DESCRIPTION
**Pull request by Neeke**
Add cloudwise to training and support page

### CODE REVIEW

**Comment by Neeke** [comment]
Add cloudwise to training and support page.

Cloudwise is a unicorn enterprise located in China in the field of operations and maintenance. We have provided professional services such as operation and maintenance software and experts to thousands of enterprises. When creating operational value for the enterprise, we strongly recommend using Promethus to solve customer problems, and when customers encounter problems using Promethus, we provide professional level services to ensure that customers can use Promethus correctly.

**Comment by juliusv** [comment]
@Neeke Thanks! A couple of notes:

* We try to keep the list alphabetically sorted, could you update the ordering?
* The link (https://www.cloudwise.sg/page/aiops120.html) currently gives me a "404 Not Found" error, could you make sure that it's the right one?
* If possible, we recommend vendors to link to a Prometheus-specific page so that customers can find out what Prometheus-related offerings you have specifically. Not sure if the current intended page has that, since I can't view it.

**Comment by Neeke** [comment]
> 



> @Neeke Thanks! A couple of notes:
> 
> * We try to keep the list alphabetically sorted, could you update the ordering?
> * The link (https://www.cloudwise.sg/page/aiops120.html) currently gives me a "404 Not Found" error, could you make sure that it's the right one?
> * If possible, we recommend vendors to link to a Prometheus-specific page so that customers can find out what Prometheus-related offerings you have specifically. Not sure if the current intended page has that, since I can't view it.

Thank you for your feedback. I will make the necessary modifications as soon as possible to avoid your review.

> @Neeke Thanks! A couple of notes:
> 
> * We try to keep the list alphabetically sorted, could you update the ordering?
> * The link (https://www.cloudwise.sg/page/aiops120.html) currently gives me a "404 Not Found" error, could you make sure that it's the right one?
> * If possible, we recommend vendors to link to a Prometheus-specific page so that customers can find out what Prometheus-related offerings you have specifically. Not sure if the current intended page has that, since I can't view it.

Thank you for your feedback. I will make the necessary modifications as soon as possible to avoid your review.

**Comment by Neeke** [comment]
@juliusv  Hi

-  I try to keep the list alphabetically sorted, and update the ordering, please check it again.
-  The link is update to "https://www.cloudwise.sg/service/aiops120/", and in the first visual section of the main body, the page specifically proposes technical support services for Prometheus.

Perhaps you can check and pass this PR, if there is any confusion, you can explain again.

**Comment by juliusv** [comment]
Thanks, yes, looks good now :+1:

**Pull request merged**
