### PR TITLE
Last 2.18.0 release step: Adding docs version.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by roidelapluie** [comment]
triggered redeploy

**Comment by beorn7** [comment]
Timed out again. Do we need more resources in Netlify? I guess just by rendering the docs for more and more Prometheus releases, we are hitting the limit. (Just educated guessing, I didn't do any research.) Or we _could_ say that's a reason to prune some older releases from the docs.

**Comment by roidelapluie** [comment]
> Timed out again. Do we need more resources in Netlify? I guess just by rendering the docs for more and more Prometheus releases, we are hitting the limit. (Just educated guessing, I didn't do any research.) Or we _could_ say that's a reason to prune some older releases from the docs.

We don't even have AM releases doc.

**Comment by bwplotka** [comment]
hmmmm let's retry maybve?

**Comment by bwplotka** [comment]
Don't have perms @beorn7 , maybe it's just a flake

**Comment by beorn7** [comment]
We already tried a retry.
I'll try a retry again, but at some point we have to try stop trying…

**Comment by bwplotka** [comment]
We can always ask Netflify support friends. If you add me to the team I can start some discussion.

**Comment by beorn7** [comment]
I think I'm just using the prometheus-bot credentials from our password store.

I'm actually not very fluid in netlify usage. Perhaps one of our own experts can help? @juliusv might be one, or at least he might know who the experts are.

**Comment by juliusv** [comment]
I mean the build almost finishes, but times out after 20 minutes. The free plan timeout is apparently 15 minutes, but maybe we get 20 because we're on some Enterprise plan? I don't see settings around timeouts though. But 20 minutes is really long, and nanoc is really, really slow (aside from the Prometheus repo downloads at different version tags). Maybe drop the oldest Prometheus version for now?

**Comment by roidelapluie** [comment]
I would not drop 1.8. However between some releases it is possible that changes to docs were only minor.

**Comment by beorn7** [comment]
Yes, let's keep 1.8 in any case. Some people might be stuck with it.

But there is really little reason to still run 2.0 or 2.1. Let's keep the last 10 minor releases for a major release for now?

If somebody really needs the older docs, they are still there in GH, just not served on the site.

**Comment by roidelapluie** [comment]
I do agree.

**Comment by juliusv** [comment]
Yup, sounds good!

**Comment by bwplotka** [comment]
ack, will update. 

Also for versioning docs I think we will have soon answer for Hugo! :+1: 

https://github.com/thanos-io/thanos/pull/2554

cc @thisisobate

**Comment by thisisobate** [comment]
@bwplotka  Sure! Super excited to work on this versioning for Hugo.

This is a work in progress!

**Comment by bwplotka** [comment]
Addressed. PTAL @beorn7 @juliusv

**Pull request merged**
