### PR TITLE
Add GopherCon talk to media page.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@beorn7

**Comment by fabxc** [comment]
+1

**Comment by beorn7** [comment]
The whole section is titled _Resources on the Internet helpful to get started with Prometheus._ The Gophercon talk doesn't help you at all to get started with Prometheus. It's aimed at Go developers. I'm not sure if we should link it here at all.

If yes, we should have a "Misc" section that contains content remotely related to Prometheus, but which is not recommended as "getting started" materias.

**Comment by juliusv** [comment]
Closing for now then.

**Pull request closed without merging**
