### PR TITLE
Add Prom-migrator to list of integrations

### PR DESCRIPTION
**Pull request by cevian**
Prom-migrator allows users to migrate existing data between various long-term storage systems. In particular it can migrate data from any system that support remote_read to any system that supports remote_write. I think it would be useful to users and this seems like a natural place to mention this.

### CODE REVIEW

**Comment by cevian** [comment]
cc: @juliusv and thanks for the suggestion.

**Comment by juliusv** [comment]
:1: from my side, but /cc @roidelapluie for one more opinion, since I was the one suggesting this.

**Comment by roidelapluie** [comment]
I have no strong opinion on this but I would have hoped that such a tool would use more of the power of the current upstream clients (e.g. using the same config format instead of passing password in the command line), which does not seem the case.

**Comment by cevian** [comment]
@roidelapluie we are more than happy to implement any suggestions. Can you please expand on which config format you mean?

**Comment by roidelapluie** [comment]
As said, I have no strong opinion but I think it could be useful to be able to reuse prometheus remote_write and remote_read config format for such a tool.  But that is not a blocker to me, just a suggestion, and I do not know if that would be practical at all for your tool. This is 1000 feet comment :)

**Pull request merged**
