### PR TITLE
Add Rocket.Chat Alertmanager Webhook Receiver

### PR DESCRIPTION
**Pull request by codez**
Add a link for a Rocket.Chat Alertmanager webhook receiver

### CODE REVIEW

**Comment by brian-brazil** [comment]
Looks like https://github.com/pavel-kazhavets/AlertmanagerRocketChat is officially recommended: https://rocket.chat/docs/administrator-guides/integrations/prometheus/

**Comment by codez** [comment]
I actually also submitted a pull request there to include my webhook: https://github.com/RocketChat/docs/pull/1561

**Comment by brian-brazil** [comment]
We try to avoid duplicates here to encourage the community to rally around one integration, rather than continuously creating brand new ones from scratch. The other one has been around longer and seems to have more community interest, so is what should be listed.

In this case we could also just link to the official docs.

**Comment by codez** [comment]
Linking to the docs might be a good idea, so the Rocket.Chat guys can provide their preferred documentation. Shall I update my pull request?

**Comment by brian-brazil** [comment]
Please do.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
