### PR TITLE
Document Grafana integration.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc @brian-brazil @beorn7

**Comment by grobie** [comment]
Thanks, looks great.

As we haven't made any decision about the future of promdash yet, I think we should give users some orientation. Something like "Comparison with PromDash" listing and linking to advantages and limitations. The top 3 for each should be more than enough for an overview.

**Comment by juliusv** [comment]
Uhm... What would one list there? Takes way more clicks to make graphs with
Grafana than with PromDash? Grafana generally more mature, but less mature
for Prometheus?

**Comment by beorn7** [comment]
:+1: A list for orientation sounds good, but could be added later, once we have a bit more experience gathered...

**Comment by juliusv** [comment]
Merging for now, happy to accept an orientation list later.

**Pull request merged**
