### PR TITLE
Added link to Butler Config Management in integrations document.

### PR DESCRIPTION
**Pull request by mslocrian**
Hi @brian-brazil ,

I just wanted to create a PR to include the Butler CMS tool, which we use internally, as a configuration management tool for Prometheus, Alertmanager, and other tools.

I was hoping to get it included in the list.

Please let me know your thoughts.

thanks,
stegen

### CODE REVIEW

**Comment by mslocrian** [comment]
@lucperkins 

Yes, it wasn't meant to mean content management, versus configuration management. I can omit the CMS from the link in the PR, but going through the motions to get legal approval to have the tool renamed from an Adobe corporate standpoint almost makes it a non starter.

**Comment by mslocrian** [comment]
FYI, I tweaked the link in the doc. Hopefully that'll allay confusion.

**Comment by mslocrian** [comment]
@lucperkins / @brian-brazil,

Any other thoughts/concerns about this one?

Also, I'm unsure what I can do to fix the DCO check. Looks like I might want to close this PR out and re-open it, and re-sign off (without having merged in the last change accidentally).

thanks,
stegen

**Comment by lucperkins** [comment]
@mslocrian No need to close and re-open the PR! I'd say squash the commits into one, run `git commit --amend --signoff`, and then force push your amended history.

Something that saved me a lot of trouble a while back:

```shell
git config --global alias.dco 'commit --amend --signoff'
```

Now I just run `git dco` for each commit.

**Comment by brian-brazil** [comment]
Thank you for sharing. This does not appear to be a configuration management system, rather it copies files which a configuration management system has presumably produced. This is also not Prometheus specific.

I'd suggest announcing this on the -users list.

Looking at the code, I'd also suggest creating your metric objects in a `var` block, register in an `init` block, and then things will be simpler and you can get rid of the mutex.

**Comment by gouthamve** [comment]
@mslocrian I agree with Brian that this is not something that is Prometheus specific. I think the section is for tools that help users _produce_ Prometheus config. You could announce it on the `-users` list as suggested, but in the meanwhile, I am going to close the PR as it doesn't seem to be in the scope of the integrations list.

Please feel free to reopen if you think it should still be there.

**Pull request closed without merging**
