### PR TITLE
Updating line 60

### PR DESCRIPTION
**Pull request by Mohit-Nain**
Introduced line break and corrected one typo in line 60, please review and merge

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'm not seeing a diff here, what changed?

For small changes like these, one big PR is preferred to many tiny PRs.

**Comment by Mohit-Nain** [comment]
Added a comma (,) /Line break before "it can scrape and monitor its own health". 

Also changed "on a path of `/metrics`" to "on the path of `/metrics`"

**Comment by brian-brazil** [comment]
Github really doesn't make that visible...

Can you add the DCO?

**Comment by grobie** [comment]
Thank you for your contribution. Closing this pull request due to lack of recent activity, but we'd be happy if you want to pick up the work again. In that case please make the requested changes, ensure all tests pass, and re-open the PR.

**Pull request closed without merging**
