### PR TITLE
Correct bad link for Kuma integration

### PR DESCRIPTION
**Pull request by lahabana**
The link was wrong fixed it.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks, we should actually remove that link now that kuma is natively supported.

**Comment by lahabana** [comment]
While it's true it seems that prometheus docs are not versioned therefore we should probably keep both methods for a bit no?
On the Kuma side we're maintaining both methods for a bit.

**Comment by roidelapluie** [comment]
Ack

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
