### PR TITLE
Speedup build with caching navbar

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
There is a bug still

**Comment by roidelapluie** [comment]
There is a bug with the versioned content

**Comment by SuperQ** [comment]
Oof, this stuff is overly complicated to work around how slow generating takes.

**Comment by roidelapluie** [comment]
> Oof, this stuff is overly complicated to work around how slow generating takes.

The gain is ~50% so I think it is worth it. With that merged, I think we can now version alertmanager docs.

**Comment by SuperQ** [comment]
I agree, it's worth it. But, rather than spend too much time trying to speedup this build, we should continue the Hugo investigation.

**Pull request merged**
