### PR TITLE
Added Docker Hub exporter to list of third-party exporters

### PR DESCRIPTION
**Pull request by Rucknar**
Adding details of a simple Docker Hub exporter for tracking statistics about pulls/stars etc

### CODE REVIEW

**Comment by grobie** [comment]
Please have a look at https://prometheus.io/docs/practices/naming/#metric-names. Counters should end on `_total` and not `_count`.

Also have a look at https://prometheus.io/docs/instrumenting/writing_exporters/ including the section about port numbers.

**Comment by Rucknar** [comment]
Both very valid points!

I've pushed an update to the repo to resolve the counter issue and to move the tracking of stars to be a gauge from a counter. With regards to the port number, i've updated it to a new port and listed that on the wiki.

Let me know if there is anything else i've missed.

**Comment by juliusv** [comment]
@Rucknar Having the stars as a gauge is correct, but then please also omit the `_total` suffix (we only use that on counters, to distinguish them from gauges). Also, the convention is to use the plural of whatever you're counting / measuring:

* `docker_hub_pulls_total`
* `docker_hub_stars`

**Comment by juliusv** [comment]
(you may also want to update the sample metrics section in the README.md)

**Comment by juliusv** [comment]
Merging this for now...

**Comment by Rucknar** [comment]
Thanks @juliusv 

I've made the recommended adjustments above and pushed.

**Pull request merged**
