### PR TITLE
Add process-exporter to exporter.md

### PR DESCRIPTION
**Pull request by cherti**

### CODE REVIEW

**Comment by beorn7** [comment]
@ncabatoff considers his process exporter to be alpha (last time I checked).

@ncabatoff what's your current opinion? Do you feel comfortable having the exporter being listed here?

**Comment by cherti** [comment]
Ah, I wasn't aware of that.

**Comment by ncabatoff** [comment]
Yes, I'm comfortable with that, as of the changes I've made over the last week.  There's still more work planned in the form of new metrics (uptime, FD counts and limits) and adding support for a config file, but it's now got decent test coverage and I don't foresee any major breaking changes going forward.

**Comment by beorn7** [comment]
Let's merge it, then. Some of the other exporters are pretty experimental, too.

**Pull request merged**
