### PR TITLE
Add PowerDNS exporter

### PR DESCRIPTION
**Pull request by janeczku**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for the new exporter.

You should have a read of https://docs.google.com/document/d/1JapuiRbp-XoyECgl2lPdxITrhm5IyCUq9iA_h6jp3OY/edit to help your users get the most out of the exporter.

In particular:

 - Prometheus has a histogram type, you should use that for `answers_rtime_total`. It's also encouraged to put the unit as seconds, and put the unit in the metrics name. The cache hits should be merged into 0ms, and then add a separate counter for them. 
 - latency_avg_microseconds has inconsistent units with the rest, seconds are recommended. What time period is this gauge over? We strongly encourage leaving all rate calculations to be done on the Prometheus side, export the total time spent if you have it.
 - `qTypeLabelMap` doesn't seem to be used

**Comment by janeczku** [comment]
@brian-brazil  Thanks Brian for your valuable recommendations! :smiley:

**Comment by janeczku** [comment]
> Prometheus has a histogram type, you should use that for answers_rtime_total.

@brian-brazil  I looked into this:
The histogram type doesn't have a `Set()` method. That's why it cannot be used with the PowerDNS API who only exposes counters and not event streams.

**Comment by brian-brazil** [comment]
When writing an exporter you shouldn't be using the usual metric types, rather use ConstMetric.

**Comment by janeczku** [comment]
Right, but like i said, i don't have the samples for the response times, just the counts of samples for each bucket. Hence, i have no way of calculating the Sum for the ConstHistrogram metric.

**Comment by brian-brazil** [comment]
We haven't run into this particular problem before, I'd suggest putting in a 0. The sum isn't needed for the histogram to work,

**Comment by janeczku** [comment]
It isn't? Okay i will give ConstHistogram a try then!

**Comment by juliusv** [comment]
@brian-brazil Wouldn't `NaN` make more sense if the sum is unknown?

**Comment by brian-brazil** [comment]
Either could work.

**Comment by juliusv** [comment]
Right, but `NaN` more correctly expresses that we don't know what it is. `0` doesn't say "absent data", it's just wrong?

**Pull request merged**
