### PR TITLE
Add New Relic as remote write endpoint

### PR DESCRIPTION
**Pull request by B1XR11L729w583adTl5899556EJ5322a**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?

Also remote write URLs are not considered secret, so this will expose the license key.

**Comment by aepuls** [comment]
@brian-brazil It looks like John included the `signed off by` line in the commit. Do you need more for the DCO than that?

**Comment by aepuls** [comment]
We are aware that the remote write URLs are not secret but do plan to use this mechanism for now.

**Comment by brian-brazil** [comment]
Thanks!

It'd be better to use basic auth or bearer tokens, which would keep the secret secret. URLs in general are not secret.

**Comment by jgals** [comment]
For future reference, New Relic has since added support for remote write authentication via bearer tokens.

**Pull request merged**
