### PR TITLE
Alertmanager 0.21 docs

### LINKED ISSUE #1672: Remove algolia temporary workaround
https://github.com/prometheus/docs/blob/d4073d38baefbe1035ea72df3649cb37d3420854/layouts/footer.html#L27-L30

@juliusv Is it OK to remove this now?

### PR DESCRIPTION
**Pull request by roidelapluie**
cc @juliusv @simonpasquier 
closes #1672 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
how much time does it take to have include indexed @juliusv ?

**Comment by juliusv** [comment]
@roidelapluie Hm, my contact at Algolia told me that they reindex things every 24h unless they trigger things manually. It's weird though, I don't see my recent change to our Algolia config (https://github.com/algolia/docsearch-configs/commit/2c0c306f3b4139bd4bc89d45adbe9e3216b932dc#diff-faa65298ccae9f682c816a36a3e79a02) to index the `include:true|false` meta tag working yet. When I change the `facetFilters` to `['include:true']`, nothing is found. I'll check with him about that...

**Comment by roidelapluie** [comment]
looks OK now @juliusv

**Comment by juliusv** [comment]
:+1: Awesome, thanks!

**Pull request merged**
