### PR TITLE
Update clientlibs.md

### PR DESCRIPTION
**Pull request by miroswan**
Adding a new client library

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Some comments from a quick peek:

Is rendering the output over http threadsafe?

I'd allow users to not have to pass labels if they're not using them. Unlike Go, you can do function overloading in C. Similarly there's no need for inc vs add here due to overloading.

`prom_metric_sample_histogram_from_labels` - it'd be good if the user could cache this, rather than it having to be computed on every observation. Similarly for the other types.

A Summary without quantiles should be easy to add.

`promhttp_set_active_collector_registry` - I think an optional argument to `promhttp_start_daemon` would be better than a global.

**Comment by miroswan** [comment]
Hello @brian-brazil. Thanks for the good feedback. 

* Good idea regarding promhttp_start_daemon. I'll make an adjustment. 

* Do you have a proposal for the approach to overloading in C? AFAIK know it's not supported without using odd hacks. If there is a way to natively support function overloading where multiple declarations of the same function name are supported (like Java), definitely let me know. Interested. 

* Technically, users can cache metric samples in variables at compile time if they are aware of all of their labels ahead of time. We have an existing demonstration of this use-case in a staging environment. I'll update the API/Documentation to make this capability more obvious. If you're looking for more capability than what I've described, please let me know and I'll see if I can address it as well. 

* I'm interested in adding Summaries. I'll see about getting to this. 

* I _believe_ metric exposition over HTTP should be thread-safe. I haven't had any issues in my smoke tests or staging environments but I'll definitely take a closer look to make sure there aren't bugs there.

**Comment by brian-brazil** [comment]
> Do you have a proposal for the approach to overloading in C?

I must have been thinking of a different language, it's been a while since I've used pure-C.

https://stackoverflow.com/a/25026358/83591 indicates that it's possible with C11, which you already require.

**Comment by miroswan** [comment]
> https://stackoverflow.com/a/25026358/83591 indicates that it's possible with C11, which you already require.

Neat. I'll look into this more.

**Comment by brian-brazil** [comment]
> I believe metric exposition over HTTP should be thread-safe.

I didn't notice any locking when glancing over the code.

**Pull request merged**
