### PR TITLE
Added an additional link to a new ibm mq java based exporter

### PR DESCRIPTION
**Pull request by sberdyshev**
Signed-off-by: Sergey Berdyshev <sberdyshev@cinimex.ru>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. To avoid confusion for users and to encourage cooperation and discourage NIH we try to avoid duplicates in this list. How does this differ from the existing one we list, which still appears to be maintained?

**Comment by sberdyshev** [comment]
Thnks for the reviewing pr.
The main point - the exporter is written in java that allows to easily run it in AIX environment. 
I stated it here: https://groups.google.com/forum/?fromgroups#!topic/prometheus-developers/NbE7zt34aAw
As extra we tried to meet prometheus standards on metrics naming (default IBM MQ metrics names are confusing) and to provide the best docs we could offer.

**Comment by brian-brazil** [comment]
Have you talked to the maintainers of the existing exporter to take on your improvements?

**Comment by sberdyshev** [comment]
No, I haven't.
As I stated before, we wanted exporter to be java-based in order to make it possible to run it in AIX environment with no effort.

**Comment by brian-brazil** [comment]
Considering that AIX is from IBM and the existing exporter is also related to them, I'd suggest talking to them. Having an uncommon deployment scenario is not enough reason to have duplication in this list.

**Comment by brian-brazil** [comment]
Per above, we aim not to have duplicates and there's an existing maintained official exporter in this space.

**Pull request closed without merging**
