### PR TITLE
Link to Net::Prometheus client library for Perl

### PR DESCRIPTION
**Pull request by leonerd**

### CODE REVIEW

**Comment by leonerd** [comment]
> HELP needs to be escaped, the rules are slightly different to label values
> In the docs for histogram, buckets are upper bound - not lower bounds

Fixed in source.

> The content-type is missing the version and charset

I've added version (`version=0.0.4`) but I don't see docs/examples on charset.
https://prometheus.io/docs/instrumenting/exposition_formats/

> Is it possible to initialise a Summary/Histogram child?

Is there an example from another client library on what this would look like? I'm not quite sure I follow

**Comment by brian-brazil** [comment]
> charset.

https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L30

> Is there an example from another client library on what this would look like? I'm not quite sure I follow

Something like mysummary.labels("value") is the usual way, as labels both creates and returns the child.

**Comment by leonerd** [comment]
> charset

Now fixed in source too.

> Something like mysummary.labels("value") is the usual way, as labels both creates and returns the child.

Ah, if I understand correctly, then it already does that:
https://metacpan.org/pod/Net::Prometheus::Metric#labels1

**Comment by brian-brazil** [comment]
Ah, I'd missed that as it wasn't used in the label examples.

**Comment by RichiH** [comment]
Can you cut a 0.07 for your charset change, please? Thanks for all your work :)

**Pull request merged**
