### PR TITLE
Delegate a matrix server

### PR DESCRIPTION
**Pull request by SuperQ**
Delegate matrix.org as the Matrix servie for prometheus.io.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by RichiH** [comment]
Sgtm

Sent by mobile; please excuse my brevity.

**Comment by SuperQ** [comment]
First I have to figure out how to Nanoc.

**Comment by RichiH** [comment]
Any update here, or is this stale?

**Comment by SuperQ** [comment]
I think the consensus was that we don't need/want to do this because it makes all matrix channels look like they're part of prometheus.io.

**Pull request closed without merging**
