### PR TITLE
Adds ACT Fibernet Exporter

### PR DESCRIPTION
**Pull request by captn3m0**
[ACT](https://www.actcorp.in/) is a Internet Service Provider in India. The provider exposes data usage metrics by scraping it from the ACT portal website.

Looks like this in Grafana:

image

### CODE REVIEW

**Comment by brian-brazil** [comment]
You need to add the DCO before I can merge.

As a way to improve your exporter, gauges should not have a _total suffix. It's also recommended to export bytes rather than any other unit.

**Comment by RichiH** [comment]
Networks speeds are, unfortunately, normalized to using bits. In this specific case, doing calculations actually becomes more cumbersome if some data is in byets.

**Comment by brian-brazil** [comment]
This exporter is exposing usage in gigabytes. The base units remain bytes - even for network speeds (in fact that's the 2nd biggest unit that needs standardisation after seconds, mixing bits and bytes does not end well).

**Comment by captn3m0** [comment]
I wanted to use bytes as well, but it felt like giving a fake sense of accuracy since the portal reports usage in GB:

image

Can't do bits, since this is network transfer (and not network speed)

**Comment by brian-brazil** [comment]
The standard in Prometheus is always to use base units, no matter the precision. You can always mention the precision in the help string.

**Comment by captn3m0** [comment]
Will push out a new release in that case. Does this look okay?

```
# HELP act_fup_usage_bytes ACT current usage in bytes (precision is in GB)
# TYPE act_fup_usage_bytes gauge
act_fup_usage_bytes_total 41420000000

# HELP act_fup_max_bytes ACT FUP limit in bytes (precision is in GB)
# TYPE act_fup_max_bytes gauge
act_fup_max_bytes 500000000000
```

Thanks for the suggestions :100:!

**Comment by brian-brazil** [comment]
act_fup_usage_bytes_total should be act_fup_usage_bytes as it's a gauge rather than a counter.

I can't merge until you add the DCO.

**Comment by captn3m0** [comment]
- DCO is already passing (I force pushed with the amended commmit). Do I need to do something on my repo as well?
- Removed the `_total`
- Did a new `1.0.2` release with the change.

**Pull request merged**
